### PR TITLE
Fix issue in VS Code on Windows where common defs are not found

### LINKED ISSUE #751: realpath in module resolution breaks language server in multi-file cases on Windows
I'm about to submit a fix for this as it was really getting in my way as I needed to change .cadl in a lot of samples. When we change import of relative paths to use module resolution, that introduced a realpath which in turn started converting VS Code's normalized lower-case drive letters (annoying but VS Code refuses to change this) back to their canonical uppercase. 

The language server works like this:

1. Find main.cadl for the current document
2. Check that compilation of main.cadl included the current document

If either 1 or 2 fails, then the document is used as its own main file, and step 2 started failing when there are case-mismatches.

So this breaks scenarios like this:

main.cadl
```
import "./common.cadl";
import "./other.cadl";
```

common.cadl
```
model CommonType {}
```

other.cadl
```
// CommonType won't be found 
model OtherType extends CommonType {}
```

### PR DESCRIPTION
**Pull request by nguerrera**
```
The issue impacts multi-file specs where common definitions are pulled in
from main.cadl but then not seen when editing another file that relies on
that. We started calling realpath in the compiler on relative path imports,
which led to a mismatch between VS Code's lower-case normalized drive letter
and realpath's canonical upper-case drive letter.

This made the language server think that main.cadl did not import the
current file and decide that it should analyze the current file as its own
entry point.

The fix is to also use realpath in the language server whenever we receive a
path or file URL from the client.
```

Fix #751

### CODE REVIEW

File: packages/compiler/server/serverlib.ts [hunk 1]
```diff
@@ -210,14 +217,13 @@ export function createServer(host: ServerHost): Server {
...
+  const fileSystemCache = createFileSystemCache();
 
-  const compilerHost: CompilerHost = {
-    ...host.compilerHost,
-    readFile,
-    stat,
-    getSourceFileKind,
-  };
+  // File change notifications must be handled syncronously, so enqueue them
+  // here. Call processPendingFileEvents before consulting fileSystemCache.
```
Comment (nguerrera) [inline packages/compiler/server/serverlib.ts:223]: This comment is wrong. Fixing.

File: packages/compiler/core/util.ts [hunk 2]
```diff
@@ -48,6 +48,10 @@ export function deepClone<T>(value: T): T {
   return value;
 }
 
+export async function resolveRealPath(host: CompilerHost, path: string) {
+  return resolvePath(await host.realpath(path));
```
Comment (timotheeguerin) [inline packages/compiler/core/util.ts:52]:
```suggestion
  return normalizePath(await host.realpath(path));
```
Resolve path calls out to `normalizePath` + some resolution if multiple args

File: packages/compiler/server/serverlib.ts [hunk 3]
```diff
@@ -291,17 +293,17 @@ export function createServer(host: ServerHost): Server {
...
         },
       ];
     } else if (params.rootPath) {
       workspaceFolders = [
         {
           name: "<root>",
           uri: compilerHost.pathToFileURL(params.rootPath),
-          path: ensureTrailingDirectorySeparator(resolvePath(params.rootPath)),
+          path: ensureTrailingDirectorySeparator(
+            await compilerHost.realpath(resolvePath(params.rootPath))
```
Comment (timotheeguerin) [inline packages/compiler/server/serverlib.ts]:
```suggestion
            await resolveRealPath(params.rootPath)
```

I think here otherwise you might endup with windows `\`

File: packages/compiler/server/serverlib.ts [hunk 4]
```diff
@@ -1121,57 +1120,94 @@ export function createServer(host: ServerHost): Server {
...
+    return resolveRealPath(compilerHost, compilerHost.fileURLToPath(url));
+  }
+
+  function createFileSystemCache() {
+    const cache = new Map<string, CachedFile | CachedError>();
+    let changes: FileEvent[] = [];
+    return {
+      async get(path: string) {
+        for (const change of changes) {
+          const path = await fileURLToRealPath(change.uri);
```
Comment (timotheeguerin) [inline packages/compiler/server/serverlib.ts:1133]: that one is a bit annoying to have to make the cache async because of this.

File: packages/compiler/server/serverlib.ts [hunk 5]
```diff
@@ -1121,57 +1120,94 @@ export function createServer(host: ServerHost): Server {
...
+
+  function createCompilerHost(): CompilerHost {
+    const base = host.compilerHost;
+    const overrides: Partial<CompilerHost> = {
+      readFile,
+      stat,
+      getSourceFileKind,
+    };
+    const compilerHost = Object.create(base);
+    Object.assign(compilerHost, overrides);
```
Comment (timotheeguerin) [inline packages/compiler/server/serverlib.ts:1156]: any reason doing this vs just spread?

File: packages/compiler/test/path-utils.test.ts [hunk 6]
```diff
@@ -165,13 +165,6 @@ describe("compiler: path utils", () => {
     strictEqual(getBaseFileName("http://server/"), "");
     strictEqual(getBaseFileName("http://server/a"), "a");
     strictEqual(getBaseFileName("http://server/a/"), "a");
-    strictEqual(getBaseFileName("/path/a.ext", ".ext", /*ignoreCase*/ false), "a");
```
Comment (timotheeguerin) [inline packages/compiler/test/path-utils.test.ts:168]: was there anything that changed here or just removed the additional functionality that we didn't use?

File: packages/compiler/server/serverlib.ts (hunk 5 above)
Comment (nguerrera) [reply packages/compiler/server/serverlib.ts:1156]: It was so that the test could replace the base host's realpath implementation.

File: packages/compiler/test/path-utils.test.ts (hunk 6 above)
Comment (nguerrera) [reply packages/compiler/test/path-utils.test.ts:168]: I made getAnyExtensionFromPath return extension lowercased and it was confusing that there was this different ignoreCase concept that we weren't using so I deleted that.

File: packages/compiler/server/serverlib.ts (hunk 4 above)
Comment (nguerrera) [reply packages/compiler/server/serverlib.ts:1133]: Yes and it's kind of purpose defeating that we have to do some I/O to ask the file system for the real path in order to consult the cache whose purpose is to avoid repeated I/O.

File: packages/compiler/server/serverlib.ts (hunk 5 above)
Comment (timotheeguerin) [reply packages/compiler/server/serverlib.ts:1158]: wouldn't 
```
const compilerHost = {
   ...host.compilerHost,
 readFile,
      stat,
      getSourceFileKind,
```

achieve the same?

File: packages/compiler/test/path-utils.test.ts (hunk 6 above)
Comment (timotheeguerin) [reply packages/compiler/test/path-utils.test.ts:168]: ah didn't noticed this was getting called from the other function

File: packages/compiler/server/serverlib.ts (hunk 5 above)
Comment (nguerrera) [reply packages/compiler/server/serverlib.ts:1158]: Not quite `...` would copy host.compilerHost properties so any future changes to host.compilerHost would not be observed. Now normally the host.compilerHost would never change, but I did this in a test.

https://github.com/microsoft/cadl/pull/753/files#diff-84801f11cab40f293ffd92b4958894a86c9344f4bab6815ee4f648f7e099ace3R8

This is a little hacky, but I got a little fed up of plumbing options through the test infrastructure. :)

Comment (nguerrera) [reply packages/compiler/server/serverlib.ts:1158]: I added a comment. If you feel strongly, I can make it so that the test passes down its realpath implementation rather than overwrites with it.

Comment (timotheeguerin) [reply packages/compiler/server/serverlib.ts:1158]: I do feel like it be better to allow passing override in teh `createTestServerHost` instead. this feels like it will endup causing unexpected behaviors

Comment (nguerrera) [reply packages/compiler/server/serverlib.ts]: Yeah, you're right 😳

Fixed!

File: packages/compiler/server/serverlib.ts (hunk 4 above)
Comment (timotheeguerin) [reply packages/compiler/server/serverlib.ts:1133]: wonder if we could be caching the vscode path -> realpath results and when we invalidate the cache we don't need to check for realpath. 

I guess this always risk that vscode gives us a different path casing when invalidating than when we loaded first.

Comment (timotheeguerin) [reply packages/compiler/server/serverlib.ts:1133]: or maybe the cache can be case insensitive when invalidating itself.

Comment (timotheeguerin) [reply packages/compiler/server/serverlib.ts:1133]: fine keeping it like that too and see if we can improve as we go

**Review by timotheeguerin — APPROVED** [review]
