### PR TITLE
Fix: Projecting model property with type referencing sibling

### LINKED ISSUE #1289: Investigate: Allow references within interfaces and models to members defined subsequently
Investigate implementation for #804 

Core Piece of this: 
- investigate having more ahead of time symbol resolution for member types

Considerations
- Consider impact on predictable member ordering #948 
- Consider impact on decorator execution

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #1289

### CODE REVIEW

File: packages/compiler/core/projector.ts [hunk 1]
```diff
@@ -641,17 +633,4 @@ export function createProjector(
...
     return clone;
   }
-
-  /**
-   * Project the given type by projecting the parent type first.
-   * @param type Type to project.
-   * @param parentType Parent type that should be projected first.
-   * @returns Projected type
-   */
-  function projectViaParent(type: Type, parentType: Type): Type {
```
Comment (daviwil) [inline packages/compiler/core/projector.ts:651]: Not needed anymore?  Seems like I remember this being added to fix a projection bug we found in Azure.Core, but I could be wrong.

**Review by daviwil — APPROVED** [review]

File: packages/compiler/core/projector.ts (hunk 1 above)
Comment (timotheeguerin) [reply packages/compiler/core/projector.ts:651]: Yeah, that fixed it at the time but this ended up building on the problem. I do remember adding a regression test to make sure we wouldn't break it again. I'll double check this PR works fine in teh cadl-azure repo before merging

Comment (timotheeguerin) [reply packages/compiler/core/projector.ts:651]: Ok, found the problem and  it is working now
