### PR TITLE
Fix leftover reference to mixins

### LINKED ISSUE #742: Interface extends wrong type references `mix`
`mix` should be replaced by `extends`

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW50ZXJmYWNlIEZvbyBleHRlbmRzIGJsYWggew0KICANCn0%3D)

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #742

### CODE REVIEW

File: packages/compiler/core/messages.ts [hunk 1]
```diff
@@ -343,7 +343,7 @@ const diagnostics = {
   "extends-interface": {
     severity: "error",
     messages: {
-      default: "Interfaces can only mix other interfaces",
+      default: "Interfaces can only extends other interfaces",
```
Comment (bterlson) [inline packages/compiler/core/messages.ts:346]: `
```suggestion
      default: "Interfaces can only extend other interfaces",
```

**Review by daviwil — APPROVED** [review]
