### PR TITLE
Fix: Swagger UI Dropdown break UI if switched before writing cadl

### LINKED ISSUE #864: Cadl playground crash when switching to swagger UI without a spec selected.
Open https://cadlplayground.z22.web.core.windows.net/ change dropdown from `Open API` > `Swagger UI` then screen goes blank.

This only happen if there is no cadl code. We should maybe just not show the dropdown.

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #864

### CODE REVIEW

**Comment by nguerrera** [comment]
Looks like this includes #891 which makes it tricky to review.

**Comment by timotheeguerin** [comment]
ah oops, my bad, I'll do a rebase when the other PR is merged

File: packages/playground/src/components/swagger-ui.tsx [hunk 1]
```diff
@@ -6,11 +6,12 @@ export interface SwaggerUIProps {
 export const SwaggerUI: FunctionComponent<SwaggerUIProps> = (props) => {
   const uiRef = useRef(null);
   const uiInstance = useRef<any>(null);
+
   useEffect(() => {
     if (uiInstance.current === null) {
       uiInstance.current = CreateSwaggerUI({
         domNode: uiRef.current,
-        spec: JSON.parse(props.spec),
+        spec: props.spec as any,
```
Comment (timotheeguerin) [inline packages/playground/src/components/swagger-ui.tsx:14]: @types/swagger-ui types unfornatunally  are not accurate at all.

**Review by markcowl — APPROVED** [review]
