### PR TITLE
Fix issues with operation signature(interface ref, circular ref, etc.)

### LINKED ISSUE #640: Internal server error when using operation reference of interface
Simplified error found here https://github.com/microsoft/cadl/issues/637
https://cadlplayground.z22.web.core.windows.net/?c=aW50ZXJmYWNlIEZvbyB7DQogIGJhcigpOiBzdHJpbmc7DQp9DQoNCm9wxBggaXPEKC5iYXI7DQo%3D

```cadl
interface Foo {
  bar(): string;
}

op bar is Foo.bar;
```

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #640

As part of fixing this bug also found a few issues:

### Original bug

```cadl
interface Foo {
  bar(): string;
}

op bar is Foo.bar;
```
[link](https://cadlplayground.z22.web.core.windows.net/prs/703/?c=aW50ZXJmYWNlIEZvbyB7DQogIGJhcigpOiBzdHJpbmc7DQp9DQoNCm9wxBggaXPEKC5iYXI7) 
### Also gave the same compiler error when using it on model is

```cadl
model Foo {
  id: string
}
model Bar is Foo.id;
```

### Self reference with signature incorrect message
```cadl
op bar is bar;
```
image
[link](https://cadlplayground.z22.web.core.windows.net/prs/703/?c=b3AgYmFyIGlzxAc7)

### Referencing each other would produce another error 
```cadl
op foo is bar;
op bar is foo;
```
[link](https://cadlplayground.z22.web.core.windows.net/prs/703/?c=b3AgZm9vIGlzIGJhcjsNCm9wxAnEEGZvbzsNCg%3D%3D)
image

### CODE REVIEW

File: packages/compiler/core/checker.ts [hunk 1]
```diff
@@ -516,7 +516,8 @@ export function createChecker(program: Program): Checker {
       | OperationStatementNode
       | UnionStatementNode
   ): number {
-    return node.symbol!.id!;
+    // eslint-disable-next-line @typescript-eslint/no-non-null-asserted-optional-chain
+    return node.symbol?.id!;
```
Comment (nguerrera) [inline packages/compiler/core/checker.ts:520]: This is because node.symbol lies about being non-nullable? Do we not expect all of model, alias, interface, operation, union to have a node?

File: packages/compiler/core/checker.ts [hunk 2]
```diff
@@ -1182,9 +1183,8 @@ export function createChecker(program: Program): Checker {
     opReference: TypeReferenceNode | undefined
   ): OperationType | undefined {
     if (!opReference) return undefined;
-
     // Ensure that we don't end up with a circular reference to the same operation
-    const opSymId = operation.symbol ? getNodeSymId(operation) : undefined;
+    const opSymId = getNodeSymId(operation);
```
Comment (nguerrera) [inline packages/compiler/core/checker.ts:1187]: Oh, I guess this is moved into getNodeSymId. I could see myself getting confused why the if below is needed now.

File: packages/compiler/core/checker.ts (hunk 1 above)
Comment (timotheeguerin) [reply packages/compiler/core/checker.ts:520]: the node types are correct, this method is what is cheating and why we had that crash before. Could try making it it valid(`return number | undefined`) but I think that affected a bit more code in the checker. Ultimately that would be better than cheating the type system and having those kind of issue keep coming back

Comment (timotheeguerin) [reply packages/compiler/core/checker.ts:520]: I guess nvm, the type is also wrong saying there there is always a symbol

Comment (timotheeguerin) [reply packages/compiler/core/checker.ts:520]: image

**Review by nguerrera — APPROVED** [review]

File: packages/compiler/core/checker.ts (hunk 1 above)
Comment (nguerrera) [reply packages/compiler/core/checker.ts:582]: We should maybe think about making this better in the typing, but that would be out of scope for this change, and likely very disruptive.
