### PR TITLE
Fix: Various issue around parent types and sourceProperty in checker and projections

### LINKED ISSUE #462: KeysOf<T> and ParentKeysOf<T> create duplicate parameters
Currently, copyResourceKeyParameters creates new properties with different names than the original properties on a new model, but the parent .model still points to the source model. This seems like breaking an invariant and probably needs to be changed, but merely doing so makes the OpenAPI much uglier and more redundant.

This then causes the OpenAPI emitter to generate duplicate parameters and overwrite them. The problem is that there are other circumstances where you can have a duplicate parameter key (for example, with duplicate friendlyNames) where it would be an error to silently overwrite. I'm putting in a workaround to allow the overwriting only if the full JSON representation of the parameter is unchanged, and pointing back to this issue in a comment to find a long term solution.

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix [#1069](https://github.com/microsoft/cadl/issues/1069)

fix #462

### CODE REVIEW

File: packages/compiler/core/projector.ts [hunk 1]
```diff
@@ -255,6 +256,10 @@ export function createProjector(
   }
 
   function projectModel(model: Model): Type {
+    if (model.name === "Foo") {
```
Comment (nguerrera) [inline packages/compiler/core/projector.ts:259]:
```suggestion
    if (model.name === "Foo") {
```

Left over from debugging?

Comment (timotheeguerin) [reply packages/compiler/core/projector.ts:259]: indeed

File: packages/compiler/core/projector.ts [hunk 2]
```diff
@@ -324,11 +329,21 @@ export function createProjector(
...
     const projectedDecs = projectDecorators(prop.decorators);
 
-    const projectedProp = shallowClone(prop, {
+    const projectedProp: ModelProperty = shallowClone(prop, {
       type: projectedType,
       decorators: projectedDecs,
     });
 
+    if (prop.model) {
+      const parentModel = projectType(prop.model) as Model;
```
Comment (nguerrera) [inline packages/compiler/core/projector.ts:338]: Is this cast safe? IIRC, projecType can return `never`?

File: packages/compiler/core/checker.ts [hunk 3]
```diff
@@ -4243,7 +4243,7 @@ export function getEffectiveModelType(
     }
   }
 
-  return match ? getProjectedEffectiveModelType(program, match) : model;
+  return match ? match : model;
```
Comment (nguerrera) [inline packages/compiler/core/checker.ts:4246]:
```suggestion
  return match ?? model;
```

File: packages/compiler/core/projector.ts (hunk 2 above)
Comment (timotheeguerin) [reply packages/compiler/core/projector.ts:333]: I think this works right now because projecting the parent always result in getting the projection mid projection

Comment (timotheeguerin) [reply packages/compiler/core/projector.ts:333]: Could we maybe for now change those to have a `compilerAssert` and then we can revisit if this ever happen?

Comment (nguerrera) [reply packages/compiler/core/projector.ts:333]: Sound good.

**Review by nguerrera — APPROVED** [review]

File: packages/compiler/core/projector.ts (hunk 2 above)
Comment (bterlson) [reply packages/compiler/core/projector.ts]: I agree that this should be safe.

Comment (nguerrera) [reply packages/compiler/core/projector.ts]: I see. I missed the explaanation. I don't feel strongly about adding the asserts, then, but it couldn't hurt.

**Review by bterlson — APPROVED** [review]

File: packages/samples/test/output/rest/petstore/openapi.json [hunk 4]
```diff
@@ -184,10 +184,10 @@
         "description": "Creates or update a instance of the extension resource.",
         "parameters": [
           {
-            "$ref": "#/components/parameters/Pet.petId"
+            "$ref": "#/components/parameters/Pet.id"
           },
           {
-            "$ref": "#/components/parameters/Checkup.checkupId"
+            "$ref": "#/components/parameters/Checkup.id"
```
Comment (nguerrera) [inline packages/samples/test/output/rest/petstore/openapi.json:190]: Hmm, in the diff I saw in chat, things got inlined which seemed fine, but now I'm wondering if referencing Checkup.id for parameter named checkupId is OK. Is it possible to produce a repro where Checkup.id is used as a parameter directly and as a key parameter with a different name than it had orinally and in that case will we hit the duplicate name error?

Comment (timotheeguerin) [reply packages/samples/test/output/rest/petstore/openapi.json:190]: message after, the change was to include the sourceProperty in `copyKeysProperties` which then cause the openapi emitter logic to keep tracing the property back to its source

File: packages/rest/src/resource.ts [hunk 5]
```diff
@@ -118,7 +118,6 @@ function cloneKeyProperties(context: DecoratorContext, target: Model, resourceTy
       decorators,
       optional: false,
       model: target,
-      sourceProperty: keyProperty,
```
Comment (nguerrera) [inline packages/rest/src/resource.ts]: I wonder if this needs to be explicitly unset sourceProperty so we don't inherit it?

**Review by nguerrera — APPROVED** [review]
