### PR TITLE
Fix rendering of tables in docs with newlines in content

### LINKED ISSUE #1605: Parameters table doesn't render correctly for multi-line descriptions:
image

Renders as:
image

It doesn't matter how many spaces you do (or don't) put for a hanging indent. If you put everything on a single line it works, but for all practical purposes we need to handle multi-line comments appropriately.

### PR DESCRIPTION
**Pull request by nguerrera**
The compiler was handling newlines in a tag fine, refined a test to confirm, but the issue was when we spit out a markdown table that newline gets through to the output unescaped and messes things up.

The fix here is to replace `"\n"` with `"<br />"`

Fix #1605

### CODE REVIEW

File: packages/ref-doc/src/utils/markdown.ts [hunk 1]
```diff
@@ -23,7 +23,7 @@ export function inlinecode(code: string) {
 }
 
 function escapeMarkdownTable(text: string) {
-  return text.replace(/(\|)/g, "\\$1");
+  return text.replace(/(\|)/g, "\\$1").replace("\n", "<br />");
```
Comment (nguerrera) [inline packages/ref-doc/src/utils/markdown.ts:26]: This will only replace the first `\n`, won't it? Oops. Let me see if I can add a test.

File: packages/ref-doc/src/utils/markdown.ts [hunk 2]
```diff
@@ -23,7 +23,7 @@ export function inlinecode(code: string) {
 }
 
 function escapeMarkdownTable(text: string) {
-  return text.replace(/(\|)/g, "\\$1");
+  return text.replace(/(\|)/g, "\\$1").replace(/\n/g, "<br />");
```
Comment (bterlson) [inline packages/ref-doc/src/utils/markdown.ts:26]: Pedantically, `<br />` wastes bytes over `<br>`, the self-closing tag syntax is an xhtml holdover that isn't necessary in HTML5 (which, if you're curious, always ignores trailing whitespace and slashes, and maintains a list of "void elements" that don't need any closing syntax for things like `img` and `br`).

Comment (bterlson) [reply packages/ref-doc/src/utils/markdown.ts:26]: Continuing aside - this results in the annoyance that custom elements can't ever be self-closing, i.e. `<my-custom-element />` is valid syntax but is semantically identical to `<my-custom-element>`, i.e. it is unclosed.

**Review by bterlson — APPROVED** [review]

File: packages/ref-doc/src/utils/markdown.ts (hunk 2 above)
Comment (nguerrera) [reply packages/ref-doc/src/utils/markdown.ts:26]: I will double check, but I think it barfed at me when I did `<br>` first.

Comment (nguerrera) [reply packages/ref-doc/src/utils/markdown.ts:26]: This auto-merged before I could double check, but indeed, something in the stack does not like `<br>`.

```
Compiled with problems:X

ERROR in ../../docs/compiler/reference/decorators.md

Module build failed (from ../../common/temp/node_modules/.pnpm/@docusaurus+mdx-loader@2.3.0_de61d8f3d8ac64703c5df6ba8f9598df/node_modules/@docusaurus/mdx-loader/lib/index.js):
SyntaxError: C:\Src\cadl\docs\compiler\reference\decorators.md: Expected corresponding JSX closing tag for <br>. (295:96)
```

Comment (bterlson) [reply packages/ref-doc/src/utils/markdown.ts:26]: Ohhhhh because this is JSX (an html-like syntax embedded in JS) not html. Interesting, ok. Yeah jsx is more xhtml like.

Comment (bterlson) [reply packages/ref-doc/src/utils/markdown.ts:26]: Ohhhhh because this is JSX (an html-like syntax embedded in JS) not html. Interesting, ok. Yeah jsx is more xhtml like.

Comment (nguerrera) [reply packages/ref-doc/src/utils/markdown.ts:26]: Ah, yes, I totally understood this when I made this change, and didn't like blindly futz with it until it worked. 🤣
