### PR TITLE
Fix: Using causing duplicate symbol errors even if not used

### LINKED ISSUE #79: Experience problems with collisions between namespaces
Consider this:

```cadl
using A;
using B;

namespace A {
  model M {} // error here
}

namespace B {
  model M {} // and here
}

model Foo {
  m: M; 
}
```
```
C:\t\main.cadl:5:3 - error duplicate-symbol: Duplicate name: "M"
C:\t\main.cadl:9:3 - error duplicate-symbol: Duplicate name: "M"
```

This is misleading because M is not "duplicated" until you use both namespaces. It also means you can't have `using A` and `using B` together even when you never reference the colliding names or always fully qualify them.

Now look at morally equivalent C#, where I would argue the experience is much better. I think we should make things work this way.

``` C#
using A;
using B;

namespace A {
  class M {}
}

namespace B {
  class M {}
}

class Foo {
  M m; // error here
}
```
```
C:\t\Program.cs(13,3,13,4): error CS0104: 'M' is an ambiguous reference between 'A.M' and 'B.M'
```

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #79 
Change how usings are being resolved.

## Before: 
Usings would inject the target namespace exports into the locals which could cause duplicate symbols

This would cause duplicate symbols.
```
using Cadl.Rest;
using Cadl.Rest.Resource;
using Cadl.Http;
```

## Now:
When using a `using` it will only keep a reference to the target namespace. When it is time to resolve a reference it will look for all the usings and check if that reference exists in each one and only report an issue if there is twice the same.

Example: 

```
import "@cadl-lang/rest";

using Cadl.Rest;
using Cadl.Rest.Resource;
using Cadl.Http;

namespace Foo {
  @delete("some") op do(): int32;
}
```
image

## Duplicate using

Using twice the same thing will cause an error instead of having duplicate/ambiguous reference
image

## Auto complete changes
If there is a potential duplicate the autocomplete will list potential options scoped by the interface
image

image

Todo: 
- [x] autocomplete
- [x] add error if using twice the same namespace
- [x] Tests

### CODE REVIEW

File: packages/compiler/core/messages.ts [hunk 1]
```diff
@@ -344,6 +344,12 @@ const diagnostics = {
       default: paramMessage`Duplicate name: "${"name"}"`,
     },
   },
+  "ambiguous-symbol": {
+    severity: "error",
+    messages: {
+      default: paramMessage`"${"name"}" is an ambiguous name between ${"duplicateNames"}`,
```
Comment (timotheeguerin) [inline packages/compiler/core/messages.ts:350]: more descriptive

File: packages/compiler/core/checker.ts [hunk 2]
```diff
@@ -871,9 +872,36 @@ export function createChecker(program: Program): Checker {
...
+
+      // check "global scope" usings
+      if (scope.usingsRefs) {
+        const bindings = scope.usingsRefs
+          .map((x) => ({
+            binding: resolveIdentifierInTable(node, x.exports!, resolveDecorator),
+            namespace: x,
+          }))
+          .filter((x) => x.binding !== undefined);
+        // binding = resolveIdentifierInTable(node, scope.locals, resolveDecorator);
```
Comment (timotheeguerin) [inline packages/compiler/core/checker.ts:887]: remove

**Comment by bterlson** [comment]
This is good stuff! I like the resulting behavior.

Implementation wise I'm concerned about adding an additional loop in identifier resolution, and in general making iguring out all the bindings in a scope more complex. These tend to be very hot paths also for member completions and potentially other static analysis. I think it's important we exit the binder with a complete picture about what things are in scope without needing more computation. 

Another approach might be to use symbol flags. Symbols from usings are flagged and if we are about to declare it again, we set a duplicate using flag on the symbol. Then we can quickly check for the flag during resolution and emit the proper error as you've done.

Thoughts?

**Comment by timotheeguerin** [comment]
That would work too, could change the `locals` type to include that ambiguous flag.

Regarding your points:
- the current behavior was injecting the `using` exports in the checker and not during the binding stage so this doesn't actually change really
- the auto complete is a good point(missed that change). Though it is already going through multiple scope(navigating all the parent scopes to find it + the global scope) in both the autocomplete list and the resolution.

I guess we can do that but there is would still be some inconsistency on what is available in the scope or we need to fix that for everything and at that point it might become quite a large matrix of reference from everywhere increasing the size of the syntax tree.

If you think the main issue is the loop, can definitely just go with this flagged map approach.

**Comment by bterlson** [comment]
IIRC we are doing the usings merging in the checker but during initialization, so it's a one time cost not per identifier lookup? But you're right that we don't have a complete picture of locals once the binder is done.

I can't look on mobile right now but I thought we had symbol flags on the symbol itself already? Might just need to add the fromUsing and duplicateUsing flag there.

**Comment by timotheeguerin** [comment]
I don't see flags on the symbol only `NodeFlags` but might not be looking at the right place.

On a slightly related note when working on making the syntax tree readonly all the symbols and mapping get added after and prevent the tree from being fully immutable.
As there is 3 stage to the production of the semantic model we could redesign that a little to have the syntax tree actually immutable and better types(`locals` and `exports` are not always optional)

1. Create syntax tree => CadlScriptNode | Immutable
2. Run binder => Add symbols, exports, locals references to a copy of the tree(new types) => BoundedCadlScriptNode | Immutable?
3. Run checker => produce semantic model from the bounded nodes but doesn't touch the syntax tree

**Comment by timotheeguerin** [comment]
@bterlson updated the PR to not have the loop. I had to make a new type `UsingSymbolTable` which keeps track of all the symbols with the same key. Had to do this because the basic `SymbolTable` doesn;t keep a list of the symbol having duplicates for the same name. And this is kind of needed so the diagnostics can report all the duplicate namespaces.

When resolving an identifier it will then get the symbols for the given name and if there is more than one it will report the diagnostics.

**Review by bterlson — APPROVED** [review]
Looks excellent to me!

File: packages/compiler/core/checker.ts [hunk 3]
```diff
@@ -80,7 +81,16 @@ export interface Checker {
   getTypeName(type: Type): string;
   getNamespaceString(type: NamespaceType | undefined): string;
   cloneType<T extends Type>(type: T): T;
-  resolveCompletions(node: IdentifierNode): Map<string, Sym>;
+  resolveCompletions(node: IdentifierNode): Map<string, CadlCompletitionItem>;
+}
+
+export interface CadlCompletitionItem {
```
Comment (daviwil) [inline packages/compiler/core/checker.ts:87]:
```suggestion
export interface CadlCompletionItem {
```

File: packages/compiler/core/checker.ts [hunk 4]
```diff
@@ -961,9 +1031,9 @@ export function createChecker(program: Program): Checker {
   function checkProgram() {
     program.reportDuplicateSymbols(globalNamespaceNode.exports);
     for (const file of program.sourceFiles.values()) {
-      program.reportDuplicateSymbols(file.locals);
+      // program.reportDuplicateSymbols(file.locals);
```
Comment (daviwil) [inline packages/compiler/core/checker.ts:1034]: Should these two commented lines be removed?

File: packages/compiler/core/checker.ts [hunk 5]
```diff
@@ -1776,13 +1855,13 @@ export function createChecker(program: Program): Checker {
...
     if (scope.locals) {
       console.log(`${Array(indent * 2).join(" ")}-locals:`);
-      for (const [name, sym] of scope.locals) {
-        console.log(
-          `${Array(indent * 2 + 1).join(" ")}${name} => ${
-            sym.kind === "type" ? SyntaxKind[sym.node.kind] : "[fn]"
-          }`
-        );
-      }
+      // for (const [name, sym] of scope.locals) {
```
Comment (daviwil) [inline packages/compiler/core/checker.ts:1858]: Remove?

File: packages/compiler/core/program.ts [hunk 6]
```diff
@@ -225,10 +225,10 @@ export async function createProgram(
     const cadlScript = loadCadlScriptSync(sourceFile);
     checker.mergeCadlSourceFile(cadlScript);
     checker.setUsingsForFile(cadlScript);
-    reportDuplicateSymbols(cadlScript.locals);
+    // reportDuplicateSymbols(cadlScript.locals);
```
Comment (daviwil) [inline packages/compiler/core/program.ts:228]: Remove?

**Review by daviwil — APPROVED** [review]
Looks great!
