### PR TITLE
Fix: Missing @key  on resource create error instead of duplicate route

### LINKED ISSUE #220: Duplicate operation error when resource is missing key
We should issue a better diagnostic in this case. The duplicate error is very confusing.

```
import "@cadl-lang/rest";
import "@cadl-lang/openapi3";

using Cadl.Rest;
using Cadl.Rest.Resource;
using Cadl.Http;

interface Dogs mixes ResourceOperations<Dog, PetStoreError> {}

model Dog {}

model PetStoreError {
  @statusCode code: "default";
}
```

```
C:/Src/cadl/packages/rest/lib/resource.cadl:36:3 - error @cadl-lang/rest/duplicate-operation: Duplicate operation "get" routed at "get /".
C:/Src/cadl/packages/rest/lib/resource.cadl:102:3 - error @cadl-lang/rest/duplicate-operation: Duplicate operation "list" routed at "get /".
```

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix  #220

This adds a decorator to validate the condition of the template param. Until we have better generic constraints there isn't  much else we can do.

The error will show up on the resource itself instead of the mixes which is where it would have made sense but right now there isn't a good way to do that.
image

### CODE REVIEW

**Comment by bterlson** [comment]
While the outcome isn't the greatest, I think this is a cool pattern and if we just had a good way to target errors from decorators, this would be super useful.

File: packages/rest/test/test-resource.ts [hunk 1]
```diff
@@ -253,4 +253,21 @@ describe("rest: resources", () => {
...
+      using Cadl.Rest.Resource;
+
+      interface Dogs mixes ResourceOperations<Dog, {}> {}
+
+      model Dog {}
+      `
+    );
+    expectDiagnostics(diagnostics, {
+      code: "@cadl-lang/rest/missing-key",
+      message: "Type 'Dog' is missing but requires one. Use @key to mark the property key.",
```
Comment (nguerrera) [inline packages/rest/test/test-resource.ts:270]: There's at least a missing word here. Missing ___. 

I'm thinking about different wordings too.

**Comment by nguerrera** [comment]
This is definitely a major improvement and at least far less confusing than status quo. It would be better to squiggle `ResourceOperations<~~Dog~~, X>` but that is harder to locate.

> if we just had a good way to target errors from decorators, this would be super useful.

@bterlson Say more about this? decorators can specify any target already, the problem is that it's often hard for them to know what target makes sense or they might know in principle, but the code to compute it in practice can vary from painful to impossible . Maybe that's what you mean, but I don't know how we can "just have" a fix for this.

File: packages/rest/test/test-resource.ts (hunk 1 above)
Comment (nguerrera) [reply packages/rest/test/test-resource.ts:270]: How about:

> Type `Dog` is used as a resource and therefore must have a key. Use @key to designate a property as the key.

**Comment by nguerrera** [comment]
Yes, I was saying from the beginning of this issue when I filed this, that if we had some form of template constraints we could solve this, but I felt I was not understood at the time, lol.

**Comment by nguerrera** [comment]
This result still has "action at a distance": Type `ResourceOperations<Dog, X>` in one file, cause an error on Dog in another file. If Dog is file is not open, you won't get any immediate feedback in IDE unless you also set up a watch build.

**Comment by nguerrera** [comment]
To be clear, I'm not pushing back, this is still way better than status quo.

**Comment by nguerrera** [comment]
Do we have another issue tracking improving this even more so that we identify the problem at the point of template instantiation? It could track generic constraints, or at least track that we still want this specific situation to be even better. I don't want to lose this problem if we close #220.

**Comment by timotheeguerin** [comment]
> Do we have another issue tracking improving this even more so that we identify the problem at the point of template instantiation? It could track generic constraints, or at least track that we still want this specific situation to be even better. I don't want to lose this problem if we close #220.

I'll create a new issue for template constraints and link that use case to be improved
