### PR TITLE
Fix issues with comments in auto-formatter

### LINKED ISSUE #117: Multiline comment crash prettier
Comment that caused the issue
```
/*
Issues: 
- 200 instead of 204 for delete
*/
```

### LINKED ISSUE #119: Comment in empty model format outside
```
model Foo {
  // Some comment
} 
```

gets formatted to 
```
model Foo {
  // Some comment
} 

```

probably needs to check before formatting model to be empty if it contains a comment

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #119
fix #117

### 1.Fixes issues with empty model & interface with comments inside:

```cadl
model Foo {
 // Comments
}

interface Ops {
 // Comments
}
```

would get formatted to 
```
model Foo {}
// Comments

interface Ops {}
// Comments
```

### 2.Fix crash when having a comment in an empty anonymous model

```cadl
model Foo {
 nested: {
   // This comment crash prettier as it didn't know how to render it
  }
}
```

### 3. Fix crash when having multiline comments

Having a multiline comment without each line starting with `*` would crash
```cadl
/**
 some 
comment
 */
model Foo { }
```

### CODE REVIEW

File: packages/compiler/formatter/print/printer.ts [hunk 1]
```diff
@@ -528,6 +558,7 @@ export function printModelExpression(
   const inBlock = isModelExpressionInBlock(path);
 
   if (inBlock) {
+    console.log("will print", path.getValue());
```
Comment (daviwil) [inline packages/compiler/formatter/print/printer.ts:561]: Not needed?

File: packages/compiler/formatter/print/printer.ts [hunk 2]
```diff
@@ -817,3 +847,59 @@ export function printNumberLiteral(
...
+        (
+          (flags & CommentCheckFlags.Leading && !comment.leading) ||
+          (flags & CommentCheckFlags.Trailing && !comment.trailing) ||
+          (flags & CommentCheckFlags.Dangling && (comment.leading || comment.trailing)) ||
+          (flags & CommentCheckFlags.Block && !isBlockComment(comment)) ||
+          (flags & CommentCheckFlags.Line && !isLineComment(comment)) ||
+          (flags & CommentCheckFlags.First && index !== 0) ||
+          (flags & CommentCheckFlags.Last && index !== comments.length - 1)
+        )
+        // (flags & CommentCheckFlags.PrettierIgnore && !isPrettierIgnoreComment(comment)) ||
```
Comment (daviwil) [inline packages/compiler/formatter/print/printer.ts:893]: Not needed?

**Review by daviwil — APPROVED** [review]
Nice, thanks for fixing these!
