### PR TITLE
Fix Empty operation response with children resulting in 204

### LINKED ISSUE #328: Union base type with no properties produce no output
```
import "@cadl-lang/rest";

op read(): A;

@discriminator("foo")
model A {
}

model B extends A {
  foo: "B";
  b: string;
}

model C extends A {
  foo: "C";
  c: string;
}

```

Result in 
```json
"/": {
      "get": {
        "operationId": "read",
        "parameters": [],
        "responses": {
          "204": {
            "description": "No Content"
          }
        }
      }
    }
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKb3AgcmVhZCgpOiBBOwoKQGRpc2NyaW1pbmF0b3IoImZvbyIpCm1vZGVsIEEgewp9CscNQiBleHRlbmRzxRcgIGZvbzogIkIiOwogIGI6IHN0cmluZzvKMEPVMEPFMGPMMA%3D%3D)

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #328

### CODE REVIEW

File: packages/compiler/core/semantic-walker.ts [hunk 1]
```diff
@@ -279,6 +279,20 @@ export function mapChildModels(program: Program): ReadonlyMap<ModelType, readonl
   return map;
 }
 
+const ChildModelMap = Symbol();
+/**
+ * @returns the mapping of parent model to child model.
+ * Will cache the value so it is computed only once.
+ */
+export function getChildModelMap(program: Program): ReadonlyMap<ModelType, readonly ModelType[]> {
```
Comment (timotheeguerin) [inline packages/compiler/core/semantic-walker.ts:287]: Not sure if anyone else has a better idea for caching this. I think this might cause some issue with projections. Maybe we need to have a per projection cache?

File: packages/compiler/core/semantic-walker.ts [hunk 2]
```diff
@@ -279,6 +279,20 @@ export function mapChildModels(program: Program): ReadonlyMap<ModelType, readonl
   return map;
 }
 
+const ChildModelMap = Symbol();
+/**
+ * @returns the mapping of parent model to child model.
+ * Will cache the value so it is computed only once.
```
Comment (nguerrera) [inline packages/compiler/core/semantic-walker.ts:285]: I worry about this because Program is mutable. How does one invalidate the cache?

Comment (nguerrera) [reply packages/compiler/core/semantic-walker.ts:285]: oh I see, it's on the program

Comment (nguerrera) [reply packages/compiler/core/semantic-walker.ts:285]: actually, still a potential problem since the program map isn't reset if program is mutated.

File: packages/rest/src/responses.ts [hunk 3]
```diff
@@ -94,7 +95,11 @@ function processResponseType(
         const allProperties = (p: ModelType): ModelTypeProperty[] => {
           return [...p.properties.values(), ...(p.baseModel ? allProperties(p.baseModel) : [])];
         };
-        if (allProperties(responseModel).some((p) => !isResponseMetadata(p))) {
+        const childMap = getChildModelMap(program);
```
Comment (nguerrera) [inline packages/rest/src/responses.ts:98]: If we're keeping this should the openapi emitter use it too and should we expose mapChildModels?

File: packages/compiler/core/semantic-walker.ts (hunk 2 above)
Comment (timotheeguerin) [reply packages/compiler/core/semantic-walker.ts:285]: yeah, I think we need to discuss on how to cache things in the program. Right now we still have the issue that if you call `getRoutes` twice it will recompute all the routes and emit the same diagnostics twice.

However would that be an issue? In `onValidate` or `onEmit` you shouldn't be mutating the program(You can right now but you shouldn't no?) I think if we really have something where we want to mutate the program we should have another hook that will be able to mutate and then we can invalidate all cache after/during it?

File: packages/rest/src/responses.ts (hunk 3 above)
Comment (timotheeguerin) [reply packages/rest/src/responses.ts:98]: Yes, if this make sense to keep this i;'ll update the openapi emitters.

File: packages/compiler/core/semantic-walker.ts (hunk 2 above)
Comment (nguerrera) [reply packages/compiler/core/semantic-walker.ts:285]: You're right that you shouldn't mutate in onValidate or onEmit, but I was thinking more if a decorator decided to call this as decorators can add types currently.

This probably does need more discussion. I suppose it's possible to expose different surface to decorators and onXxx but also complex. The other extreme is to just live with it and say don't do that, but I worry about the footgun potential and it becomes really hard to document what you can't and can't do where.

Comment (timotheeguerin) [reply packages/compiler/core/semantic-walker.ts:285]: Could do that to start:
- Create a new `cache` entry in the program especially meant to cache things.
- We could clear the cache before onValidate and in between each decorator.
- This now introduce an potential performance issue if you think you can use some heavy cached value but it is not cached. So maybe we can have a flag to emit warning when using a cached value in a decorator so you can track those issues.

Or we skip the cache clear between decorator for now but now instead of a perf issue we could just get confusing bugs.

Comment (bterlson) [reply packages/compiler/core/semantic-walker.ts:285]: I haven't thought about this issue super deeply but I am concerned about adding any caching here, and caching as a solution to duplicate errors feels like solving the problem at the wrong layer. Would love to discuss in more detail in a meeting.

Comment (timotheeguerin) [reply packages/compiler/core/semantic-walker.ts:285]: Created an issue for this https://github.com/microsoft/cadl/issues/368. Do you want to have a dedicated meeting for this or should we just discuss this in a design meeting. Feels like there is some brainstorming to do which might not be the right fit.

File: packages/rest/src/responses.ts (hunk 3 above)
Comment (timotheeguerin) [reply packages/rest/src/responses.ts:98]: This has been replaced by https://github.com/microsoft/cadl/pull/415

File: packages/compiler/core/semantic-walker.ts (hunk 2 above)
Comment (timotheeguerin) [reply packages/compiler/core/semantic-walker.ts]: Resolved via the derivedModels

**Comment by timotheeguerin** [comment]
Removed the caching and uptook the new derivedModels property

**Review by nguerrera — APPROVED** [review]
