### PR TITLE
Fix giving a default value to custom numeric scalar

### LINKED ISSUE #1571: bug: Unable to assign default value for scalar type definition
The following code with create an internal compiler error:

```typescript
import "@cadl-lang/rest";
import "@cadl-lang/openapi3";

using Cadl.Http;

@minValue(0)
scalar MaskBits extends int32

model SubnetAllocation {
  maskBits?: MaskBits = 27;
}

@route("/network/allocations")
namespace NetworkManagement {
  op list(): SubnetAllocation[];
}
```

Error:

```text
Cadl compiler v0.39.0

Internal compiler error!
File issue at https://github.com/microsoft/cadl

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at isNumericLiteralRelatedTo (file:///home/ladmin/work/rest-api-specs-cadl/node_modules/@cadl-lang/compiler/dist/core/checker.js:3567:38)
    at isRelatedToScalar (file:///home/ladmin/work/rest-api-specs-cadl/node_modules/@cadl-lang/compiler/dist/core/checker.js:3514:21)
    at isSimpleTypeAssignableTo (file:///home/ladmin/work/rest-api-specs-cadl/node_modules/@cadl-lang/compiler/dist/core/checker.js:3546:20)
    at isTypeAssignableTo (file:///home/ladmin/work/rest-api-specs-cadl/node_modules/@cadl-lang/compiler/dist/core/checker.js:3462:37)
    at checkDefault (file:///home/ladmin/work/rest-api-specs-cadl/node_modules/@cadl-lang/compiler/dist/core/checker.js:2133:40)
    at checkModelProperty (file:///home/ladmin/work/rest-api-specs-cadl/node_modules/@cadl-lang/compiler/dist/core/checker.js:2096:46)
    at checkModelProperties (file:///home/ladmin/work/rest-api-specs-cadl/node_modules/@cadl-lang/compiler/dist/core/checker.js:1739:33)
    at checkModelStatement (file:///home/ladmin/work/rest-api-specs-cadl/node_modules/@cadl-lang/compiler/dist/core/checker.js:1676:9)
    at checkModel (file:///home/ladmin/work/rest-api-specs-cadl/node_modules/@cadl-lang/compiler/dist/core/checker.js:1614:20)
    at getTypeForNode (file:///home/ladmin/work/rest-api-specs-cadl/node_modules/@cadl-lang/compiler/dist/core/checker.js:312:24)
```

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #1571

### CODE REVIEW

File: packages/compiler/core/checker.ts [hunk 1]
```diff
@@ -4631,30 +4628,29 @@ export function createChecker(program: Program): Checker {
...
-  ) {
-    if (targetIntrinsicType === "numeric") return true;
+  function isNumericLiteralRelatedTo(source: NumericLiteral, target: Scalar) {
+    // if the target does not derive from numeric, then it can't be assigned a numeric literal
+    if (!areScalarsRelated(target, getStdType("numeric"))) {
+      return false;
+    }
+
+    // With respect to literal assignability a custom numeric scalar is
+    // equivalent to its nearest Cadl.* base. Adjust target accordingly.
```
Comment (nguerrera) [inline packages/compiler/core/checker.ts:4638]: For a minute I thought maybe we shouldn't do this because the custom type can have a narrower range than its closest core type, but then I realized it is morally equivalent to assigning string/boolean literals to custom scalars that extend string/boolean core type. Just as we wouldn't consider `@maxLength` for custom string, we will not consider `@minValue` for custom int32, etc.

**Review by bterlson — APPROVED** [review]

File: packages/compiler/test/checker/scalar.test.ts [hunk 2]
```diff
@@ -41,4 +47,68 @@ describe("compiler: models", () => {
...
+      strictEqual(S.kind, "Scalar" as const);
+      strictEqual(M.kind, "Model" as const);
+      const p = M.properties.get("p");
+      ok(p);
+      expectIdenticalTypes(p.type, S);
+      strictEqual(p.default?.kind, "Number" as const);
+      strictEqual(p.default.value, 42);
+    });
+
+    it("allows boolean scalar to have a default value", async () => {
```
Comment (nguerrera) [inline packages/compiler/test/checker/scalar.test.ts:67]:
```suggestion
    it("allows custom boolean scalar to have a default value", async () => {
```
