### PR TITLE
Fix issue with set.add is not a function

### LINKED ISSUE #1559: TypeError: set.add is not a function
I discovered this while updating cadl-azure-core for deprecations and the changes due to #1519. 
```
TypeError: set.add is not a function
    at addDependency (file:///E:/repos/cadl-azure/core/packages/versioning/src/validate.ts:36:11)
    at Object.model (file:///E:/repos/cadl-azure/core/packages/versioning/src/validate.ts:50:11)
    at Object.emit (file:///E:/repos/cadl-azure/core/packages/compiler/core/semantic-walker.ts:144:43)
```

Surprisingly, nothing in the microsoft/cadl versioning tests exercised this logic in the way that cadl-azure-core does. The method, as written, sacrifices type info, so neither the compiler not unit tests caught this even though this method was not touched in #1519.

### PR DESCRIPTION
**Pull request by tjprescott**
Fixes #1559.

### CODE REVIEW

File: packages/versioning/src/validate.ts [hunk 1]
```diff
@@ -21,20 +21,17 @@ import {
 } from "./versioning.js";
 
 export function $onValidate(program: Program) {
-  const namespaceDependencies = new Map();
+  const namespaceDependencies = new Map<Namespace | undefined, Set<Namespace>>();
```
Comment (tjprescott) [inline packages/versioning/src/validate.ts:24]: This resulted in bugs because it loses the Typescript compiler's ability to catch issues. It would be good if we could use a linter rule to prohibit these kinds of patterns that let things get treated as `any` and just allow anything to happen

**Review by nguerrera — APPROVED** [review]

File: packages/versioning/test/versioned-dependencies.test.ts [hunk 2]
```diff
@@ -912,17 +892,14 @@ describe("versioning: dependencies", () => {
...
         }
-
         @versioned(Versions)
         namespace Lib.One {
           enum Versions { v1: "v1" }
         }
         
         @useDependency(Lib.One.Versions.v1)
         namespace Lib.Two { }
-
```
Comment (tjprescott) [inline packages/versioning/test/versioned-dependencies.test.ts:925]: I think this was all autoformatter... not sure why it did this.

Comment (nguerrera) [reply packages/versioning/test/versioned-dependencies.test.ts:925]: Weird since this is inside strings. I noticed but didn't mind either way.

**Review by daviwil — APPROVED** [review]
