### PR TITLE
Fix issues with @added and @removed versioning decorators

### LINKED ISSUE #1369: @added and @removed do not work if used multiple times
https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmciOwoKdXNpbmcgQ2FkbC5WyRk7CgpAxydlZCjHGHMpCkBzZXJ2aWNlKHsKICB0aXRsZTogIldpZGdldCBTxhsiLAp9KQpuYW1lc3BhY2UgRGVtb8cbOwoKZW51bSDIUCDERiJ2MSIsxQgyxwgzxwg0xwg1xwg2xFvtALFIdHRwO8wRUmVzdDsKCm1vZGVsIFRlc3TFY0BhZGTrAMcudjIpxBZyZW1vds0YM8UY0C411y42xBh2YWw6IGludDMyO%2BQAnUByb3V0ZSgiL3TkAX8pCm9wIGdldOQAiigpOuUAkjsK

While the scenario is contrived, it should work:
```
model Test {
          @added(Versions.v2)
          @removed(Versions.v3)
          @added(Versions.v5)
          @removed(Versions.v6)
          val: int32;
        }
```

However, in the playground, `val` does not reappear in v5 as expected. This is similar to #1142, but the fix is likely a little more involved because of the interplay between the two decorators.

### PR DESCRIPTION
**Pull request by tjprescott**
Fixes #1369 so that `@added` and `@removed` can be used multiple times on a symbol.

- Deprecates `addedAfter` and `removedOnOrBefore` since these assumed a single version
- Adds `existsOnVersion` which returns a boolean whether a given symbol should exists for a given version

### CODE REVIEW

File: packages/versioning/src/versioning.ts [hunk 1]
```diff
@@ -528,15 +545,81 @@ export function getVersions(p: Program, t: Type): [Namespace, VersionMap] | [] {
...
+
+  const allVersions = getVersion(p, namespace)?.getVersions();
+  return allVersions?.sort((a, b) => a.index - b.index);
+}
+
+function getFirst(arr: Version[]): Version | undefined {
+  if (!arr.length) return undefined;
+  if (arr.length > 1) {
+    // TODO: Error?
+  }
```
Comment (tjprescott) [inline packages/versioning/src/versioning.ts:575]: Ideally this should be part of the validation.

File: packages/versioning/src/versioning.ts [hunk 2]
```diff
@@ -528,15 +545,81 @@ export function getVersions(p: Program, t: Type): [Namespace, VersionMap] | [] {
...
+): Map<string, boolean> {
+  const avail = new Map<string, boolean>();
+  // something isn't available by default
+  let isAvail = false;
+  for (const ver of all) {
+    const add = getFirst(added.filter((x) => x.index === ver.index));
+    const rem = getFirst(removed.filter((x) => x.index === ver.index));
+    if (add && rem) {
+      // TODO: Error?
+    }
```
Comment (tjprescott) [inline packages/versioning/src/versioning.ts:592]: Again, this should be part of the validation. It doesn't make sense to say something is added and removed in the same version.

File: packages/versioning/src/lib.ts [hunk 3]
```diff
@@ -54,7 +54,7 @@ const libDef = {
         removedBefore: paramMessage`'${"sourceName"}' was removed on version '${"sourceRemovedOn"}' but referencing type '${"targetName"}' removed in version '${"targetRemovedOn"}'.`,
         dependentRemovedBefore: paramMessage`'${"sourceName"}' was removed on version '${"sourceRemovedOn"}' but contains type '${"targetName"}' removed in version '${"targetRemovedOn"}'.`,
         versionedDependencyAddedAfter: paramMessage`'${"sourceName"}' is referencing type '${"targetName"}' added in version '${"targetAddedOn"}' but version used is ${"dependencyVersion"}.`,
-        versionedDependencyRemovedBefore: paramMessage`'${"sourceName"}' is referencing type '${"targetName"}' added in version '${"targetAddedOn"}' but version used is ${"dependencyVersion"}.`,
```
Comment (tjprescott) [inline packages/versioning/src/lib.ts:57]: This has been wrong the whole time. Added a test for this as well.

File: packages/versioning/src/versioning.ts [hunk 4]
```diff
@@ -534,15 +549,102 @@ export function getVersions(p: Program, t: Type): [Namespace, VersionMap] | [] {
...
+  program: Program,
+  type: Type
+): Map<string, Availability> | undefined {
+  const avail = new Map<string, Availability>();
+
+  const allVersions = getSortedVersions(program, type);
+  // if unversioned then everything exists
+  if (allVersions === undefined) return undefined;
+
+  let added = program.stateMap(addedOnKey).get(type) as Version[];
```
Comment (timotheeguerin) [inline packages/versioning/src/versioning.ts:606]: Can maybe make helper functions(not exported) to access the stateMap of added and removed

File: packages/versioning/src/versioning.ts [hunk 5]
```diff
@@ -534,15 +549,102 @@ export function getVersions(p: Program, t: Type): [Namespace, VersionMap] | [] {
...
+  const removed = (program.stateMap(removedOnKey).get(type) as Version[]) ?? [];
+  if (added === undefined && removed.length === 0) return undefined;
```
Comment (timotheeguerin) [inline packages/versioning/src/versioning.ts:608]: why can added be undefined but removed not? do you need the `?? []` for removed, wouldn't that be the same result?

File: packages/versioning/src/versioning.ts [hunk 6]
```diff
@@ -534,15 +549,102 @@ export function getVersions(p: Program, t: Type): [Namespace, VersionMap] | [] {
...
+  if (added === undefined) {
+    added = [allVersions[0]];
+  }
+
+  // something isn't available by default
+  let isAvail = false;
+  for (const ver of allVersions) {
+    const add = getFirst(added.filter((x) => x.index === ver.index));
```
Comment (timotheeguerin) [inline packages/versioning/src/versioning.ts:616]:
```suggestion
    const add = added.find((x) => x.index === ver.index);
```

`.find` is going to return the first entry? Or then we should make `getFirst` throw an error if and maybe do the filter itself

File: packages/versioning/src/versioning.ts [hunk 7]
```diff
@@ -534,15 +549,102 @@ export function getVersions(p: Program, t: Type): [Namespace, VersionMap] | [] {
...
+    const rem = getFirst(removed.filter((x) => x.index === ver.index));
+    if (add && rem) {
+      throw Error(`type cannot be added and removed on the same version ${ver.name}`);
```
Comment (timotheeguerin) [inline packages/versioning/src/versioning.ts:619]: Don't `throw Error` either emit  a dianostic if this is something that could happen or use `compilerAssert` to show that this is never a state that should happen(in theory)

File: packages/versioning/lib/decorators.cadl [hunk 8]
```diff
@@ -12,9 +12,7 @@ extern dec removed(target: unknown, version: EnumMember);
 extern dec renamedFrom(target: unknown, version: EnumMember, oldName?: string);
 extern dec madeOptional(target: unknown, version: EnumMember);
 
-extern fn addedAfter(target: unknown, version: EnumMember): boolean;
-extern fn removedOnOrBefore(target: unknown, version: EnumMember): boolean;
+extern fn existsOnVersion(target: unknown, version: EnumMember): boolean;
```
[the remark this answers is not in the document]
Comment (tjprescott) [reply packages/versioning/lib/decorators.cadl:15]: changed to `existsAtVersion` 👍

File: packages/versioning/lib/versioning.cadl [hunk 9]
```diff
@@ -178,21 +146,15 @@ projection model#v {
 #suppress "projections-are-experimental"
 projection enum#v {
   to(version) {
-    if addedAfter(self, version) {
-      return never;
-    } else if removedOnOrBefore(self, version) {
+    if !existsOnVersion(self, version) {
```
[the remark this answers is not in the document]
Comment (tjprescott) [reply packages/versioning/lib/versioning.cadl:149]: Yes 🥂

File: packages/versioning/src/versioning.ts [hunk 10]
```diff
@@ -534,15 +549,102 @@ export function getVersions(p: Program, t: Type): [Namespace, VersionMap] | [] {
...
+  );
   const appliesAt = appliesAtVersion(getRemovedOn, p, type, version);
   return appliesAt === null ? false : appliesAt;
 }
 
+function getSortedVersions(p: Program, t: Type): Version[] | undefined {
+  const [namespace, _] = getVersions(p, t);
+  if (namespace === undefined) return undefined;
+
+  const allVersions = getVersion(p, namespace)?.getVersions();
```
[the remark this answers is not in the document]
Comment (tjprescott) [reply packages/versioning/src/versioning.ts:571]: Good point. I removed that part and renamed this to just `getAllVersions`.

File: packages/versioning/src/versioning.ts (hunk 7 above)
Comment (tjprescott) [reply packages/versioning/src/versioning.ts:619]: Updated the logic so that removed trumps added.

File: packages/versioning/src/versioning.ts (hunk 6 above)
Comment (tjprescott) [reply packages/versioning/src/versioning.ts:616]: Perfect. Didn't know about this API :)

File: packages/versioning/src/versioning.ts (hunk 5 above)
Comment (tjprescott) [reply packages/versioning/src/versioning.ts:608]: I updated the logic so added won't be undefined so that way added and removed are treated the same. Let me know what you think of the updated logic.

File: packages/versioning/src/versioning.ts (hunk 4 above)
Comment (tjprescott) [reply packages/versioning/src/versioning.ts:606]: Or should they be exported?  That's why I didn't make helper functions, but right now, `getAddedOn` just says it's deprecated. It doesn't actually give an alternative. Should I expose the analogous correct helper?

File: packages/versioning/src/versioning.ts [hunk 11]
```diff
@@ -160,14 +173,16 @@ export function getNameAtVersion(p: Program, t: Type, v: ObjectType): string {
  * @returns version when the given type was added if applicable.
  */
 export function getAddedOn(p: Program, t: Type): Version | undefined {
```
[the remark this answers is not in the document]
Comment (tjprescott) [reply packages/versioning/src/versioning.ts:175]: I didn't want to move them around because of the effect it would have on the diff, but I can and should definitely create a tracking issue to remove these in March.

[the remark this answers is not in the document]
Comment (timotheeguerin) [reply packages/versioning/src/versioning.ts:175]: Sounds good, I would also add `@deprecated` in the jsdoc that will make it show up as deprecated.

File: packages/versioning/src/versioning.ts (hunk 4 above)
Comment (timotheeguerin) [reply packages/versioning/src/versioning.ts]: its mostly so the code is cleaner and you don't have to do the `as ...` type casting inside a function logic.

**Review by timotheeguerin — APPROVED** [review]

File: packages/versioning/src/versioning.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (tjprescott) [reply packages/versioning/src/versioning.ts:175]: Updated.

File: packages/versioning/src/versioning.ts (hunk 4 above)
Comment (tjprescott) [reply packages/versioning/src/versioning.ts]: I guess if folks want an updated helper we can add them in the future as a non-breaking change.

Comment (tjprescott) [reply packages/versioning/src/versioning.ts]: Added these helpers but didn't export them.
