### PR TITLE
Convert Ref objects to ref string in OpenAPI YAML output

### LINKED ISSUE #1546: OpenAPI3 emitter generates $refs incorrectly in yaml output
The OpenAPI3 emitter recently added support for output to yaml, but the $ref's produced in yaml output use incorrect structure -- the ref is formatted as an object with a "value" rather than simply as a string.  E.g.
```
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref:
                  value: '#/components/schemas/Error'
```
should be
```
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
```
[Playground link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKICB2ZXJzaW9uOiAiMS4wLjAiLAp9KQpuYW1lc3BhY2UgRGVtb8cvOwoKbW9kZWwgx0bEWUB2aXNpYmlsaXR5KCJyZWFkIiwgInVwZGF0ZSIpxCBwYXRoCiAgaWQ6IHN0cmluZzsKICB3ZWlnaHQ6IGludDMyxBFjb2xvcjogInJlZCIgfCAiYmx1ZSI7Cn0KCkBlcnJvcsd5RcQMxXhjb2Rly0BtZXNzYWdlymTEOnJvdXRlKCIvd%2BUAr3MiKQpAdGFnKOcBBcQQaW50ZXJm5ADnxxTFXEDkAN1saXN0KCk6xxlbXSB8xn7EbsUh5ADtKOUA3%2BsA3ckxzS9wb3N0IGNyZWF0ZSguLi7GItcrYXRjaCDmAUHfLEBkZWxldGUgxgf0AIt2b2lkzTLnARJ7aWR9L2FuYWx5emUiKecAoMcQ1EjGCcpKfQo%3D)

### PR DESCRIPTION
**Pull request by daviwil**
This issue fixes #1546 which reports that the OpenAPI emitter's new YAML output encodes `$ref`s as a sub-object with a `value` property.  This change uses the `replacer` option of `yaml.dump` to ensure that `Ref` objects get written out correctly as a string path.

### CODE REVIEW

**Review by nguerrera — APPROVED** [review]
Looks good. Thanks for jumping on this. If we're going to do this as hotfix, should target a branch as described here: https://github.com/Azure/cadl-azure/blob/main/CONTRIBUTING.md#make-a-patch-release

**Comment by nguerrera** [comment]
Yep, discriminator mapping:

https://cadlplayground.z22.web.core.windows.net/prs/1552/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0KDQp1c2luZyBDYWRsLkh0dHA7DQpAc2VydmljZSh7DQogIHRpdGxlOiAiV2lkZ2V0IFPGHCIsxBx2ZXJzaW9uOiAiMS4wLjDEFX0pDQpuYW1lc3BhY2UgRGVtb8cyxW1AZGlzY3JpbWluYXRvcigia2luZCIpDQptb2RlbCBQIMVyxBU6IHN0cmluZzsNCn3EOcYhUSBleHRlbmRzzisiUeQAy8soUtcoUskob3AgdGVzdCgpOiBQOw0K

File: packages/openapi3/src/openapi.ts [hunk 1]
```diff
@@ -1464,7 +1464,12 @@ function serializeDocument(root: OpenAPI3Document, fileType: FileType): string {
     case "json":
       return prettierOutput(JSON.stringify(root, null, 2));
     case "yaml":
-      return yaml.dump(root, { noRefs: true });
+      return yaml.dump(root, {
+        noRefs: true,
+        replacer: function (key, value) {
+          return key === "$ref" && value instanceof Ref ? value.value! : value;
```
Comment (nguerrera) [inline packages/openapi3/src/openapi.ts:1470]: I think this would fix the discriminator mapping issue by not checking key, and preserve the assert in Ref.toJSON() when emitting Yaml.

```suggestion
          return value instanceof Ref ? value.toJSON() : value;
```

Comment (daviwil) [reply packages/openapi3/src/openapi.ts]: Thanks!

Comment (nguerrera) [reply packages/openapi3/src/openapi.ts]: Hmm, I'm still seeing it on playground, which "try it" claims to have updated, checking

Comment (nguerrera) [reply packages/openapi3/src/openapi.ts]: "Unresolving" only to show conversation.

Hmm, but the need to rebaseline looks promising, maybe the playground update didn't work for some reason.

image

Comment (nguerrera) [reply packages/openapi3/src/openapi.ts]: Nevermind it's working now, some sort of delay from time it is pushed to playground and time it is reflected in browser, I guess.

**Comment by nguerrera** [comment]
I think this just needs another regen-samples to fix the sample outputs that have discriminator mappings (hopefully just that).

**Review by nguerrera — APPROVED** [review]

File: packages/openapi3/src/openapi.ts (hunk 1 above)
Comment (daviwil) [reply packages/openapi3/src/openapi.ts]: Yeah, I've noticed that before too
