### PR TITLE
Fix various issues with template types with errors

### LINKED ISSUE #294: Template parameters self reference stack overflow
While looking at #250 made a typo and got a stack overflow. Seems like another case we forgot in #241

Having a template with arg self ref `Foo<A = A>` cause the stack overflow.

Full failing
```cadl
import "@cadl-lang/rest";

using Cadl.Http;

@get op read(): Foo<"A">;

model Foo<A = A, B = "abc"> {
  a: A;
  b: B;
}
```

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #294 

Issues fixed: 
- [x] Stackoverflow when template default self reference itself `Foo<A = A>`
- [x] Duplicate diagnostics in circular reference of a templated type. `model Foo<T> is Foo<T>` Would create 1 diagnostic + 1 per different instantiation
- [x] Crash when templated alias self references = `alias Foo<T> = Foo<T>`. 
- [ ] Duplicate diagnostics when error in a templated type
   - [x]  unknown identifier `model Foo<A> { a: A;  b: stringw}`

### CODE REVIEW

**Comment by bterlson** [comment]
Approach seems sound. I wonder if we should do a blanket update across the entire checker to cache types prior to fully instantiating them? It would turn stack overflow errors into getting a type that isn't fully initialized (which may then result in an error, but may not), which seems always preferable?

**Comment by timotheeguerin** [comment]
Yeah so this is already the case for alias and models. Might need to do this for interfaces as well. Or were you thinking of something doing that even earlier somehow?

However this fix is actually not completely correct it break instantiation of the template(It always return the template param now instead of the value). Trying to solve, it's a bit tricky to figure out the circular reference when instantiating the template.

File: packages/compiler/test/checker/templates.ts [hunk 1]
```diff
@@ -179,14 +179,15 @@ describe("compiler: templates", () => {
     testHost.addCadlFile(
       "main.cadl",
       `
-        @test model A<T, X = T> { a: T, b: X }
-        model B { 
+        model A<T, X = T> { a: T, b: X }
+        @test model B {
```
Comment (bterlson) [inline packages/compiler/test/checker/templates.ts:183]: Hmm, is this change necessary? I feel like the previous way should work as well...

Comment (timotheeguerin) [reply packages/compiler/test/checker/templates.ts:183]: Yeah I think it still works, I can revert.
As I was trying to solve this problem I got this test failing and thought it was because of this. I am a bit confused on why it works. Wouldn't the model be returned be the uninstantiated template?
Or this just work because there is a single instantiation of A and the @test decorator just act this way?

Comment (bterlson) [reply packages/compiler/test/checker/templates.ts:183]: It's the latter. `@test` is basically last-wins for each type name. We run decorators when the model gets instantiated, and since there is only one instantiation, A will happen to be what you want to test in this case. I kind of like this test approach because it's sensitive to changes in decorator+instantiation logic which at least previously was an area of buggyness.

Comment (timotheeguerin) [reply packages/compiler/test/checker/templates.ts:183]: make sense, are you saying you like the way the test was defined before?

**Comment by timotheeguerin** [comment]
@bterlson regarding the general issues with templates errors it looks like duplicate error due to instantiation is quite common. I fixed it for the model but wondering if in general we should only be doing the checking for the generic type and not emit any error when instantiating it.

File: packages/compiler/test/checker/templates.ts (hunk 1 above)
Comment (bterlson) [reply packages/compiler/test/checker/templates.ts:183]: yeah I like the way it was before, but considering that we probably have pretty good coverage for decorators+templated types elsewhere I would be fine keeping the change. It does add more verbosity though!

**Comment by bterlson** [comment]
Can you give me an example of a remaining error?

In general, without generic constraints, I worry that we won't really be able to check much in that first pass...

**Comment by timotheeguerin** [comment]
https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgRm9vPEE%2BIHsKIGE6IEE7CiBiOiBzdHJpbmd3Owp9CgrGJkJhcsQjIGZvbzrFM8YjPjsKfQ%3D%3D

image

**Comment by bterlson** [comment]
I think I see things more clearly now.

One thing is, aside from cases where declarations merge and maybe other exotic cases, non-local changes shouldn't introduce errors into the declaration. The error should show up on the instantiation, not on the template being instantiated.

I think with that understanding in place, your original suggestion makes a lot of sense - a template with an error in it at instantiation time should probably just result in an error type when it is instantiated.

**Comment by timotheeguerin** [comment]
So in typescript it does still try to keep the object as intact as possible, convering the example above to ts equivalent, still preserve pretty much everything and just show a single error on stringw not being valid. It says it is of type `stringw` but I think behind the scene it treat it as `any` as you can assign that to anything. So I think this becomes related to you other suggestion where we could use `any` instead of `error` type for a lot of things and not have to deal with errors as much when we have subtype supertype relations.

image

File: packages/compiler/core/checker.ts [hunk 2]
```diff
@@ -677,7 +715,19 @@ export function createChecker(program: Program): Checker {
     args: Type[]
   ): Type {
     const symbolLinks = getSymbolLinks(templateNode.symbol);
-    const cached = symbolLinks.instantiations!.get(args) as ModelType;
+    if (symbolLinks.instantiations === undefined) {
+      const type = getTypeForNode(templateNode);
+      if (isErrorType(type)) {
+        return errorType;
+      } else {
+        throw new Error(
```
Comment (markcowl) [inline packages/compiler/core/checker.ts:723]: What is the impact of throwing an error here?  Does it end checker execution and allow the language server to recover?  If not, do we want the language server itself to throw an exception / crash under these circumstances (i.e. this is totally unrecoverable)?

File: packages/compiler/test/checker/model.ts [hunk 3]
```diff
@@ -73,6 +78,27 @@ describe("compiler: models", () => {
...
+        model A<T> {t: T, invalid: notValidType }
+
+        model Bar {
+          instance1: A<string>;
+          instance2: A<int32>;
+        }
+        `
+    );
+    const diagnostics = await testHost.diagnose("main.cadl");
+    expectDiagnostics(diagnostics, [
```
Comment (markcowl) [inline packages/compiler/test/checker/model.ts:94]: does this test function limit the diagnostics to just this one, or could other diagnostics have been reported?

**Review by markcowl — CHANGES_REQUESTED** [review]
Looks good.  A couple of questions about implementation and tests.

File: packages/compiler/test/checker/model.ts (hunk 3 above)
Comment (timotheeguerin) [reply packages/compiler/test/checker/model.ts:94]: this function does check that there is exactly those diagnostics. Will give a good error message if there is more or less with the list of all the diagnostics so you can resolve the other cases.

File: packages/compiler/core/checker.ts (hunk 2 above)
Comment (timotheeguerin) [reply packages/compiler/core/checker.ts:723]: So right now it was crashing with accessing undefined property. I really don't know when this scenario can happen apart from the isErrorType which I covered but this is to have a better error message in case it ever does that another undefined error.
@nguerrera fixed the language server to recover on crashes like that.

Comment (nguerrera) [reply packages/compiler/core/checker.ts:723]: This is OK, but I suggest compilerAssert(false,... for cases where you believe something can't happen but want a good message if it ever does. This makes it easier to scrub and make sure we aren't using exceptions for diagnostics.

**Review by markcowl — APPROVED** [review]
