### PR TITLE
Fix error location of duplicate property from spread

### LINKED ISSUE #744: Incorrect error location for duplicate property from spread
[Playground Link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/prs/1730/?c=bW9kZWwgRm9vIHsgeDogc3RyaW5nIH0NCsYZQmFyzBksIC4uLsUufQ%3D%3D)

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #744

### CODE REVIEW

File: packages/compiler/testing/test-server-host.ts [hunk 1]
```diff
@@ -81,17 +81,34 @@ export async function createTestServerHost(options?: TestHostOptions) {
...
+  const source = sourceWithCursor.replace(marker, "");
   return { source, pos };
 }
 
+/**
+ * Takes source code with start and end positions indicated by given marker
+ * ("~~~" by default) and returns the source without the markers along with
+ * the start and end positions.
+ */
+export function extractSquiggles(
```
Comment (timotheeguerin) [inline packages/compiler/testing/test-server-host.ts:103]: oh haha made the same change in https://github.com/microsoft/cadl/pull/749

**Review by timotheeguerin — APPROVED** [review]

File: packages/compiler/testing/test-server-host.ts (hunk 1 above)
Comment (nguerrera) [reply packages/compiler/testing/test-server-host.ts:103]: :)

Comment (nguerrera) [reply packages/compiler/testing/test-server-host.ts:103]: Haha, I promised you I'd do it if I needed it a second time last time around, so making good on it.
