### PR TITLE
Fix: Namespace and Non-namespace types should have unique names

### LINKED ISSUE #1110: namespace name cannot be the same as interface name
A namespace cannot have the same name as an interface at the same level.

[Playground Repro](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKQHNlcnZpY2UoewogIHRpdGxlOiAiV2lkZ2V0IFPGGyIsCn0pCm5hbWVzcGFjZSBEZW1vxxs7CnVzaW5nIENhZGwuSHR0cDsKCm1vZGVsIMdDxFZAa2V5IGlkOiBzdHJpbmc7CiAgd2VpZ2h0OiBpbnQzMsQRY29sb3I6ICJyZWQiIHwgImJsdWUiOwp9CgpAZXJyb3LHVkXEDMVVY29kZctAbWVzc2FnZcpkfQrrALLmAI3nALQge30KCmludGVyZtMc5ACw5AC5bGlzdCgpOscfW10gfMZ9xG1Acm91dGUoInfFHHMve2lkfSIpxjhyZWFkKEBwYXRo6wDzyUjNRnBvc3QgY3JlYXRlKEBib2R5IMQFyCvWNMd6Y3VzdG9tR2V0yHfJEeoAtMo4fQo%3D)

I don't think we need to support this, but right now we don't document that this is not allowed so least it should be documented.

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #1110

It was that if the namespace was declared after a type with the same name it wasn't checking the symbol was a namespace and would just merge its content into the symbol.

### CODE REVIEW

File: packages/compiler/core/binder.ts [hunk 1]
```diff
@@ -30,13 +30,14 @@ import { mutate } from "./util.js";
 // Use a regular expression to define the prefix for Cadl-exposed functions
 // defined in JavaScript modules
 const DecoratorFunctionPattern = /^\$/;
-
+let idCounter = 0;
```
Comment (nguerrera) [inline packages/compiler/core/binder.ts:33]: Was this for debugging?

Comment (timotheeguerin) [reply packages/compiler/core/binder.ts]: yeah, removed it now

**Review by nguerrera — APPROVED** [review]

**Review by bterlson — APPROVED** [review]
