### PR TITLE
Fix: Playground in safari

### LINKED ISSUE #923: Playground not working in safari
https://cadlplayground.z22.web.core.windows.net/ just show a blank screen.

Seems like nothing gets loaded

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #923
https://github.com/microsoft/cadl/pull/861

### CODE REVIEW

File: packages/playground/src/core.ts [hunk 1]
```diff
@@ -1,5 +1,17 @@
 export async function importCadlCompiler(): Promise<typeof import("@cadl-lang/compiler")> {
   // We need to do this so the compiler loaded is the same as the one loaded by the bundled libraries.
   const name = "@cadl-lang/compiler";
-  return import(/* @vite-ignore */ name) as any;
+  return importShim(name) as any;
+}
+
+/**
+ * Dynamic imports with importmap unfotunatelly do not work on all browsers.
```
Comment (nguerrera) [inline packages/playground/src/core.ts:8]:
```suggestion
 * Dynamic imports with importmap unfotunately do not work on all browsers.
```

**Review by nguerrera — APPROVED** [review]
