### PR TITLE
Fix additional circular ref issues(Alias, template)

### LINKED ISSUE #133: OpenAPI emitters can't handle template pattern with recursion
Compile this:
``` cadl
import "@cadl-lang/openapi3";
import "@cadl-lang/rest";

using Cadl.Http;

model ErrorTemplate<T> {
  @doc("Error code.") code: T;
  innererror?: InnerError;
}

model Error is ErrorTemplate<ErrorCode> {}
model InnerError is ErrorTemplate<InnerErrorCode> {}

enum ErrorCode {
  A,
  B,
  C
}

enum InnerErrorCode {
  C,
  D,
  E
}

@route("/")
namespace N {
  op M(): Error;
}
```

Get this:
```
TypeError: Cannot set properties of undefined (setting 'description')
    at getSchemaForModel (file:///C:/Temp/aqe/node_modules/@cadl-lang/openapi3/dist/src/openapi.js:811:58)
    at getSchemaForType (file:///C:/Temp/aqe/node_modules/@cadl-lang/openapi3/dist/src/openapi.js:661:20)
    at emitReferences (file:///C:/Temp/aqe/node_modules/@cadl-lang/openapi3/dist/src/openapi.js:625:35)
    at Object.emitOpenAPI (file:///C:/Temp/aqe/node_modules/@cadl-lang/openapi3/dist/src/openapi.js:157:13)
    at $onBuild (file:///C:/Temp/aqe/node_modules/@cadl-lang/openapi3/dist/src/openapi.js:11:19)
    at createProgram (file:///C:/Temp/aqe/node_modules/@cadl-lang/compiler/dist/core/program.js:60:19)
    at async compile (file:///C:/Temp/aqe/node_modules/@cadl-lang/compiler/dist/core/program.js:475:12)
    at async Object.handler (file:///C:/Temp/aqe/node_modules/@cadl-lang/compiler/dist/core/cli.js:67:25)
 ```
 
If you remove the `@doc("Error code") comment, it doesn't crash, but still gives this:
```
main.cadl:6:21 - error @cadl-lang/openapi3/invalid-schema: Couldn't get schema for type TemplateParameter
``` 

The behavior in both cases is the same for cadl-autorest as cadl-lang/openapi3 so we should fix both.

### LINKED ISSUE #134: Properties disappear from OpenAPI in certain template patterns with recursion
Compile this:

```cadl
import "@cadl-lang/openapi3";
import "@cadl-lang/rest";

using Cadl.Http;

model ErrorBase {
  innererror: InnerError;
}

model Error is ErrorBase {
  code: ErrorCode; 
}

model InnerError is ErrorBase {
  code: InnerErrorCode; 
}

enum ErrorCode {
  A,
  B,
  C
}

enum InnerErrorCode {
  C,
  D,
  E
}

@route("/")
namespace N {
  op M(): Error;
}
```

Get this:

```json
{
  "schemas": {
    "Error": {
      "type": "object",
      "properties": {
        "innererror": {
          "$ref": "#/components/schemas/InnerError"
        },
        "code": {
          "$ref": "#/components/schemas/ErrorCode"
        }
      },
      "required": [
        "innererror",
        "code"
      ]
    },
    "InnerError": {
      "type": "object",
      "properties": {
        "code": {
          "$ref": "#/components/schemas/InnerErrorCode"
        }
      },
      "required": [
        "code"
      ]
    },
    "ErrorCode": {
      "type": "string",
      "enum": [
        "A",
        "B",
        "C"
      ]
    },
    "InnerErrorCode": {
      "type": "string",
      "enum": [
        "C",
        "D",
        "E"
      ]
    }
  }
}
```
    
Notice that `InnerError` model is missing the `innererror` property. The same thing happens with cadl-autorest. This might be an issue in the compiler and not the emitter and it might be related to #133

### LINKED ISSUE #139: Alias self referencing cause stack overflow
```
alias A = A;
alias A = string | A;
```

### PR DESCRIPTION
**Pull request by timotheeguerin**
Resolve more issues with circular references:

## Alias circular reference
fix #139
```cadl
alias A = A;
alias A = string | A;
```

## Issue with template circular reference
fix #133
fix #134
Those issues seems to be caused when the cirucular reference involve a non template model in a templated model

Problematic code in cadl
```cadl
import "@cadl-lang/rest";

using Cadl.Http;

model ErrorTemplate<T> {
  @doc("Error code.") code: T;
  innererror?: InnerError;
}

model Error is ErrorTemplate<ErrorCode> {}
model InnerError is ErrorTemplate<InnerErrorCode> {}

enum ErrorCode {
  A,
  B,
  C,
}

enum InnerErrorCode {
  C,
  D,
  E,
}

@route("/")
namespace N {
  op M(): Error;
}

```

Produce the following OpenAPI3:

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "(title)",
    "version": "0000-00-00"
  },
  "tags": [],
  "paths": {
    "/": {
      "get": {
        "operationId": "N_M",
        "parameters": [],
        "responses": {
          "200": {
            "description": "A successful response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Error": {
        "type": "object",
        "properties": {
          "code": {
            "$ref": "#/components/schemas/ErrorCode",
            "description": "Error code."
          },
          "innererror": {
            "$ref": "#/components/schemas/InnerError"
          }
        },
        "required": [
          "code"
        ]
      },
      "ErrorCode": {
        "type": "string",
        "enum": [
          "A",
          "B",
          "C"
        ]
      },
      "InnerError": {
        "type": "object",
        "properties": {
          "code": {
            "$ref": "#/components/schemas/InnerErrorCode",
            "description": "Error code."
          },
          "innererror": {
            "$ref": "#/components/schemas/InnerError"
          }
        },
        "required": [
          "code"
        ]
      },
      "InnerErrorCode": {
        "type": "string",
        "enum": [
          "C",
          "D",
          "E"
        ]
      }
    }
  }
}

```

### CODE REVIEW

File: packages/compiler/core/checker.ts [hunk 1]
```diff
@@ -154,7 +155,6 @@ export function createChecker(program: Program): Checker {
   // Map keeping track of the models currently being checked.
```
Comment (daviwil) [inline packages/compiler/core/checker.ts:155]: This comment can be deleted now

**Review by daviwil — APPROVED** [review]
Looks good!
