### PR TITLE
Fix completion between `.` and `)`

### LINKED ISSUE #584: Completion doesn't work on `@dec(Something.|)`
Given `@dec(Something.|)` with this cursor represented by `|`, we fail to find the missing identifier to complete. I think the assumption in the comment about it being ok to do `pos <= end` (inclusive of end position after the node) because we believed we wouldn't have adjacent non-puctuation, non-trivia is, unforuntately, wrong in the case of missing identifiers.

It works ok in the common case where you haven't typed the trailing `)` yet, which is likely why we didn't notice it until now.

Found this working on #538, but it's pre-existing.

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #584 Turns out this was limited to the case of a decorated invalid statement, which commonly happens when you type a decorator before you type the statement it will apply to. The <= end problem theorized on the bug was not the issue.

We were not using the correct position for the invalid statement. It should start where its decorators start.

### CODE REVIEW

File: packages/compiler/test/test-parser-utils.ts [hunk 1]
```diff
@@ -16,6 +12,7 @@ describe("compiler: parser utils", () => {
     ): Promise<{ root: CadlScriptNode; node: Node | undefined }> {
       const { source, pos } = extractCursor(sourceWithCursor);
       const root = parse(source);
+      dumpAST(root);
```
Comment (timotheeguerin) [inline packages/compiler/test/test-parser-utils.ts:15]: for debug?

Comment (timotheeguerin) [inline packages/compiler/test/test-parser-utils.ts:15]: for debug?

Comment (timotheeguerin) [reply packages/compiler/test/test-parser-utils.ts:15]: I think that's something we could add to eslint ban-types rule as a warning like console.log so we don't leave it

Comment (timotheeguerin) [reply packages/compiler/test/test-parser-utils.ts:15]: I think that's something we could add to eslint ban-types rule as a warning like console.log so we don't leave it

File: packages/compiler/test/test-parser-utils.ts [hunk 2]
```diff
@@ -26,8 +23,8 @@ describe("compiler: parser utils", () => {
         }
       `);
       ok(node);
-      strictEqual(node.kind, SyntaxKind.NamespaceStatement);
-      strictEqual((node as NamespaceStatementNode).id.sv, "Foo");
+      strictEqual(node.kind, SyntaxKind.NamespaceStatement as const);
```
Comment (timotheeguerin) [inline packages/compiler/test/test-parser-utils.ts:26]: does this make it that the type inference work after? This is awesome, so anyoing to have to the casting after

**Review by timotheeguerin — APPROVED** [review]

File: packages/compiler/test/test-parser-utils.ts (hunk 2 above)
Comment (nguerrera) [reply packages/compiler/test/test-parser-utils.ts:26]: Yes, I expected it to work because I thought I did it elsewhere. But turns out I was doing ok(node.kind === SyntaxKind.X, "Expected X"). This is better. :)

File: packages/compiler/test/test-parser-utils.ts (hunk 1 above)
Comment (nguerrera) [reply packages/compiler/test/test-parser-utils.ts:15]: This is actually ok to leave because dumpAST uses logVerboseTestOutput. So you can look at the output in test explorer but it doesn't pollute the console unless you set an env var. The function name could maybe be improved, though.

Comment (timotheeguerin) [reply packages/compiler/test/test-parser-utils.ts:15]: i see

**Comment by timotheeguerin** [comment]
Was just testing this an this works fine for me in main 
image

am I missing something? https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKQHNlcnZpY2VUaXRsZSgiV2lkZ2V0IFPGFSIpCm5hbWVzcGFjZSBEZW1vxxg7CnVzaW5nIENhZGwuSHR0cDsKCm1vZGVsIMdAewogIEBrZXkgaWQ6IHN0cmluZzsKICB3ZWlnaHQ6IGludDMyxBFjb2xvcjogInJlZCIgfCAiYmx1ZSI7Cn0KCkBlcnJvcsdWRcQMxVVjb2Rly0BtZXNzYWdlymTEOmZvcm1hdCjlAJ0pCmludGVyZuQAweYAnOcAw8VOQOQArGxpc3QoKTrHH1tdIHzGcMRgQHJvdXRlKCJ3xRxzL3tpZH0iKcY4cmVhZChAcGF0aOsA5slIzUZwb3N0IGNyZWF0ZShAYm9keSDEBcgr1jTHemN1c3RvbUdldMh3yRHqALTKOH0K

**Comment by nguerrera** [comment]
Yeah, I was wrong when I filed the bug, it only happens when you decorate an invalid statement. The common way to do this is type a decorator at the end of the file before you type the statement that it will apply to:

https://cadlplayground.z22.web.core.windows.net/?c=QGRlYyhDYWRsLik%3D

https://cadlplayground.z22.web.core.windows.net/prs/593/?c=QGRlYyhDYWRsLik%3D
