### PR TITLE
Fix issues with multiple copies of compiler core being loaded

### LINKED ISSUE #1625: Inconsistent behavior of cadl compile depending on which repo I run an emitter from
Here's the PR I am looking at: https://github.com/Azure/azure-rest-api-specs-pr/pull/10411

This PR is set up to use cadl-apiview 0.3.4. If I run cadl compile on this PR from the specs repo, it completes and I get an APIView. I can confirm that something isn't rendering in APIView.

Now I need to debug, so I switch to the azure-sdk-tools repo and go to the cadl-apiview folder. Here I have the same dependency versions at the PR in question and I set up launch.json so that I can run APIView on this spec and debug into that process.

```
# launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Compile Scratch",
            "program": "${workspaceFolder}/node_modules/@cadl-lang/compiler/dist/core/cli/cli.js",
            "args": [
              "compile",
              "E:/repos/azure-rest-api-specs-pr/specification/cognitiveservices/HealthDecisionSupport/client.cadl",
              "--emit=\"${workspaceFolder}\"",
            ],
            "smartStep": true,
            "sourceMaps": true,
            "skipFiles": ["<node_internals>/**/*.js"],
            "cwd": "${workspaceFolder}",
          },
    ],
}
```

However, when I run this, that same spec with the same dependencies no longer even compiles. Instead it throws errors and thus I cannot debug into the program.

```
C:\Program Files\nodejs\node.exe .\node_modules\@cadl-lang\compiler\dist\core\cli\cli.js compile E:/repos/azure-rest-api-specs-pr/specification/cognitiveservices/HealthDecisionSupport/client.cadl --emit="E:\repos\azure-sdk-tools\tools\apiview\emitters\cadl-apiview"
Cadl compiler v0.39.0
Diagnostics were reported during compilation:
E:/repos/azure-rest-api-specs-pr/specification/cognitiveservices/HealthDecisionSupport/routes/route.oncophenotype.cadl:15:3 - error @cadl-lang/rest/duplicate-operation: Duplicate operation "GetJob1" routed at "get /".
> 15 |   @summary("Get Onco Phenotype job details")
     |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 16 |   @tag("OncoPhenotype")
     | ^^^^^^^^^^^^^^^^^^^^^^^
> 17 |   @doc("Gets the status and details of the Onco Phenotype job.")
     | ^^^^^^^^^^^^^^^^^^^^^^^
> 18 |   @example("./examples/SuccessfulOncoPhenotypeResponse.json", "SuccessfulOncoPhenotypeGetAnalyzeStatus")
     | ^^^^^^^^^^^^^^^^^^^^^^^
> 19 |   GetJob1 is Azure.Core.ResourceRead<OncoPhenotypeResponse>;
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E:/repos/azure-rest-api-specs-pr/specification/cognitiveservices/HealthDecisionSupport/routes/route.trialmatcher.cadl:14:3 - error @cadl-lang/rest/duplicate-operation: Duplicate operation "GetJob2" routed at "get /".
> 14 |   @summary("Get Trial Matcher job details")
     |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15 |   @tag("TrialMatcher")
     | ^^^^^^^^^^^^^^^^^^^^^^
> 16 |   @doc("Gets the status and details of the Trial Matcher job.")
     | ^^^^^^^^^^^^^^^^^^^^^^
> 17 |   @example("./examples/SuccessfulTrialMatcherResponse.json", "SuccessfulTrialMatcherGetAnalyzeStatus")
     | ^^^^^^^^^^^^^^^^^^^^^^
> 18 |   GetJob2 is Azure.Core.ResourceRead<TrialMatcherResponse>;
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E:/repos/azure-rest-api-specs-pr/specification/cognitiveservices/HealthDecisionSupport/node_modules/@azure-tools/cadl-dpg/lib/decorators.cadl:3:1 - warning @azure-tools/cadl-azure-core/casing-style: The names of Namespace types must use PascalCase
> 3 | namespace Azure.DPG;
    | ^^^^^^^^^^^^^^^^^^^^

Found 2 errors, 1 warning.
Process exited with code 1
```

This feels very similar to this closed issue (https://github.com/microsoft/cadl/issues/1232) because it had the same symptom. Running from the spec repo behaved different than running from the azure-sdk-tools repo, but I don't know that these issues are at all related.

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #1625

### CODE REVIEW

File: packages/compiler/lib/decorators.ts [hunk 1]
```diff
@@ -961,7 +961,7 @@ export function getOverloadedOperation(
   return program.stateMap(overloadsOperationKey).get(operation);
 }
 
-const projectedNameKey = Symbol("projectedNameKey");
+const projectedNameKey = createStateSymbol("projectedNameKey");
```
Comment (tjprescott) [inline packages/compiler/lib/decorators.ts:964]: I remember @timotheeguerin saying that `Symbol("...")` does result in subtle bugs and that we should stick with `createStateSymbol`. There seem to be a lot of other instances of raw Symbol being used, most in `cadl-azure` but also in projections and a couple other places. Should we update them all?

Comment (nguerrera) [reply packages/compiler/lib/decorators.ts:964]: I looked at the others in core and they are OK. But I will look at cadl-azure.

tmlanguage-generator: completely separate tool
projection-logic.test: test only 
effective-type.test: test only
checker: for union variant name: deliberately a unique, non-shared symbol

But let me know if you see others in core that my search missed.

Comment (tjprescott) [reply packages/compiler/lib/decorators.ts:964]: Nope those were the core ones I saw. Thanks for looking 👍 

The cadl-azure ones do look to be all throughout the libraries in non-test code.

Comment (tjprescott) [reply packages/compiler/lib/decorators.ts:964]: I'm happy to make a RP

**Review by tjprescott — DISMISSED** [review]

File: packages/compiler/lib/decorators.ts (hunk 1 above)
Comment (nguerrera) [reply packages/compiler/lib/decorators.ts:964]: Yes, we should fix those in cadl-azure and thank you for offering to make the PR. I'll take you up on that. :)

**Comment by nguerrera** [comment]
I pushed more changes that actually fix #1625, but it's smelly and I'm not sure about the best way to handle it better or if this is OK.

File: packages/compiler/lib/decorators.ts (hunk 1 above)
Comment (nguerrera) [inline packages/compiler/lib/decorators.ts:964]: This one is not related to the symptom in #1625, but could result in the same sort of bug.

File: packages/rest/src/resource.ts [hunk 2]
```diff
@@ -97,10 +97,11 @@ function cloneKeyProperties(context: DecoratorContext, target: Model, resourceTy
...
     const keyName = getKeyName(program, keyProperty);
 
-    // Filter out the @visibility decorator because it might affect metadata
-    // filtering
     const decorators = [
-      ...keyProperty.decorators.filter((d) => d.decorator !== $visibility),
+      // Filter out the @visibility decorator because it might affect metadata
+      // filtering. NOTE: Check for name equality instead of function equality
+      // to deal with multiple copies of core being used.
+      ...keyProperty.decorators.filter((d) => d.decorator.name !== $visibility.name),
```
Comment (nguerrera) [inline packages/rest/src/resource.ts:104]: This is dirty and if someone had `MyNamespace.visibility`, we'd filter that too. I'm not sure of the best way to fix this or if this is maybe acceptable. cc @bterlson

Comment (tjprescott) [reply packages/rest/src/resource.ts:104]: Is there a more thorough test for "equivalence" we could apply here without falling back to name but without relying on strict equality of the function?

Comment (nguerrera) [reply packages/rest/src/resource.ts:104]: I couldn't find one that already existed. I thought about plumbing through the decorator symbol onto the DecoratorApplication and comparing getFullyQualifiedName. Somewhat expensive. I also thought about storing a symbol on $visibility function and exposing a isVisibilityDecorator from core but this pollutes public API of core and would only work when all versions of core in play are updated with the fix.

File: packages/compiler/lib/decorators.ts (hunk 1 above)
Comment (tjprescott) [reply packages/compiler/lib/decorators.ts:964]: Here's that PR: 
https://github.com/Azure/cadl-azure/pull/2556

**Review by daviwil — APPROVED** [review]

File: common/changes/@cadl-lang/rest/shared-symbol_2023-02-07-17-20.json [hunk 3]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@cadl-lang/rest",
+      "comment": "Fix issues with multiple copies of compiler core being loaded.",
```
Comment (bterlson) [inline common/changes/@cadl-lang/rest/shared-symbol_2023-02-07-17-20.json:5]: My only thought is it might be nice to be a bit more explicit about what you're fixing here.

**Review by bterlson — APPROVED** [review]

File: common/changes/@cadl-lang/compiler/shared-symbol_2023-02-07-15-24.json [hunk 4]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@cadl-lang/compiler",
+      "comment": "Fix issues with multiple copies of compiler core being loaded.",
```
Comment (nguerrera) [inline common/changes/@cadl-lang/compiler/shared-symbol_2023-02-07-15-24.json:5]:
```suggestion
      "comment": "Fix issue with projectedName decorator not working correctly when multiple copies of the are loaded.",
```

File: common/changes/@cadl-lang/rest/shared-symbol_2023-02-07-17-20.json (hunk 3 above)
Comment (nguerrera) [inline common/changes/@cadl-lang/rest/shared-symbol_2023-02-07-17-20.json:5]:
```suggestion
      "comment": "Fix issue with filtering of visibility decorator on resource key not working when multiple copies of compiler are loaded.",
```

File: common/changes/@cadl-lang/compiler/shared-symbol_2023-02-07-15-24.json [hunk 5]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@cadl-lang/compiler",
+      "comment": "Fix issue with projectedName decorator not working correctly when multiple copies of the are loaded.",
```
Comment (nguerrera) [inline common/changes/@cadl-lang/compiler/shared-symbol_2023-02-07-15-24.json:5]:
```suggestion
      "comment": "Fix issue with projectedName decorator not working correctly when multiple copies of the compiler are loaded.",
```

File: common/changes/@cadl-lang/rest/shared-symbol_2023-02-07-17-20.json [hunk 6]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@cadl-lang/rest",
+      "comment": "Fix issue with filtering of visibility decorator on resource key not working when multiple copies of compiler are loaded.",
```
Comment (nguerrera) [inline common/changes/@cadl-lang/rest/shared-symbol_2023-02-07-17-20.json:5]:
```suggestion
      "comment": "Fix issue with filtering of visibility decorator on resource key not working when multiple copies of the compiler are loaded.",
```
