### PR TITLE
Fix validation on @madeOptional

### LINKED ISSUE #1240: `@Versioning.madeOptional` should validate that a model target property is indeed optional in the version it says it was made optional
In the following spec, I would expect an error on the madeOptional since the model property is not optional in the version (v2) it makes the bold statement it having been made optional in.

```cadl
import "@cadl-lang/versioning";

@Versioning.versioned(Versions)
namespace Something;

enum Versions {
  v1,
  v2
}

model X {
  @Versioning.madeOptional(Versions.v2)
  thisIsRequired: string;
}
```

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3ZlcnNpb25pbmciOwoKQFbJDy7HGmVkKMcVcykKbmFtZXNwYWNlIFNvbWV0aGluZzsKCmVudW0gyCUgewogIHYxLMQGMgp9Cgptb2RlbCBYxRjMYG1hZGVPcHRpb25hbMljLnYyKQogIHRoaXNJc1JlcXVpcmVkOiBzdHLFa30%3D)

### PR DESCRIPTION
**Pull request by tjprescott**
Fixes #1240.

Test code:
```
import "@cadl-lang/versioning";

@Versioning.versioned(Versions)
namespace Something;

enum Versions {
  v1,
  v2,
}

model X {
  @Versioning.madeOptional(Versions.v2)
  thisIsRequired: string;
}
```

### CODE REVIEW

**Review by johanste — APPROVED** [review]

File: packages/versioning/src/versioning.ts [hunk 1]
```diff
@@ -94,12 +95,22 @@ export function $renamedFrom(context: DecoratorContext, t: Type, v: EnumMember,
...
 }
 
-export function $madeOptional(context: DecoratorContext, t: Type, v: EnumMember) {
+export function $madeOptional(context: DecoratorContext, t: ModelProperty, v: EnumMember) {
   const { program } = context;
   const version = checkIsVersion(context.program, v, context.getArgumentTarget(0)!);
   if (!version) {
     return;
   }
+  if (!t.optional) {
```
Comment (timotheeguerin) [inline packages/versioning/src/versioning.ts:104]: I can't find a repro right now but I feel like this is going to emit a diagnostic if you are projecting the older version when this is required.

Comment (timotheeguerin) [reply packages/versioning/src/versioning.ts:104]: It is probably not happening right now because the decorator still runs on the projected type before the projection makes it required but I think if we run yet another projection on top of that then it will start to complain.

Comment (timotheeguerin) [reply packages/versioning/src/versioning.ts:104]: A better way to validate that might be just to have that in the `onValidate` with the other versioning validation

Comment (tjprescott) [reply packages/versioning/src/versioning.ts:104]: It seems so much more complicated to do this inside of onValidate. It doesn't raise a diagnostic when projecting the older required version and projects it correctly as required.

Comment (timotheeguerin) [reply packages/versioning/src/versioning.ts:104]: Ok so this doesn't complain because I think the projection don't do what is expected.


If you have

```
const original = compile();
const projected1 = projectProgram(orginal);
const projected2 = projectProgram(projected1);
```

you'd expect the projection2 to run on top of the already proejcted program but it actually still runs on top of the original program

Comment (timotheeguerin) [reply packages/versioning/src/versioning.ts]: so I guess if that's expected then this is not a problem and we can keep the validation like that.

Comment (tjprescott) [reply packages/versioning/src/versioning.ts]: Relocated the logic into `onValidate`.
