### PR TITLE
Fix issue with server not locating main.cadl in parent folder

### LINKED ISSUE #541: Problems in language server with multifile specs spread across directories
In vs code, if the user represents their cadl spec using multiple files in different folders, the vs code extension reports false  errors resulting from not processing the entire spec..

For example, a structure like
- root
  main.cadl
  common.cadl
  - resources
     Foo.cadl
     Bar.cadl

where main.cadl imports all of the other files

Can result in errors when 'Foo.cadl' is opened in VS Code. For example, types referenced in 'Foo.cadl' that are defined in common.cadl or main.cadl are not found.  Also, decorators applied to a namespace in main.cadl are not recognized when the namespace is used in 'Foo.cadl', which can result in validation errors for required decorators like `@armNamespace`

If the same spec is all in one directory, these issues do not apply. ALso, if all files are opened in VSCode, this appears to fix many of the errors

Note that importing 'main.cadl' and 'foo.cadl' from the leaf directories resolves some of these issues, but does not solve them universally.

In all cases, the spec compiles correctly from the command line (using 'main.cadl or '.' as the argument to compile)

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #541

### CODE REVIEW

File: packages/compiler/test/server/server-file-handling.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+describe("compiler: server: main file", () => {
+  it("finds the main file", async () => {
+    const host = await createTestServerHost();
+    host.addCadlFile("./main.cadl", 'import "./common.cadl"; import "./subdir/subfile.cadl";');
+    host.addCadlFile("./common.cadl", "model Base {}");
+    host.addCadlFile("./subdir/empty.cadl", ""); // to force virtual file system to create directory
+    const document = host.addOrUpdateDocument("./subdir/subfile.cadl", "model Sub extends Base {}");
+
+    await host.server.checkChange({ document });
+    deepStrictEqual(host.getDiagnostics("./subdir/subfile.cadl"), [], "No diagnostics expected");
```
Comment (nguerrera) [inline packages/compiler/test/server/server-file-handling.ts:13]: Note: these are vcode-language-server diagnostics, not Cadl diagnostics, so can't use our expect diagnostic helper

File: packages/compiler/server/serverlib.ts [hunk 2]
```diff
@@ -713,6 +713,7 @@ export function createServer(host: ServerHost): Server {
   }
 
   function inWorkspace(path: string) {
+    path = ensureTrailingDirectorySeparator(path);
```
Comment (nguerrera) [inline packages/compiler/server/serverlib.ts:716]: This was the bug and I'm surprised it lurked for so long. At some point I realized that inWorkspace would lie if we workspace folder was, for example, "/foo", and we asked if "/foobar/file.cadl" was in the workspace. But I only did half the fix to guarantee that workspaceFolders have trailing separator, and missed guaranteeing the other side of the startsWith here.

File: packages/compiler/test/server/test-server-host.ts [hunk 3]
```diff
@@ -26,6 +26,7 @@ export async function createTestServerHost(): Promise<TestServerHost> {
   const diagnostics = new Map<string, Diagnostic[]>();
   const logMessages: string[] = [];
   const fileSystem = await createTestFileSystem();
+  fileSystem.compilerHost.getLibDirs = () => [];
```
Comment (nguerrera) [inline packages/compiler/test/server/test-server-host.ts:29]: Checking why this was necessary.

**Review by markcowl — APPROVED** [review]
